import type { ViewBox, RugbyPreset, PlayerChip } from './types';

export const FIELD_PAD = { x: 50, y: 50 };
export const FIELD_W = 700;
export const FIELD_H = 1000;
export const SVG_W = FIELD_W + FIELD_PAD.x * 2;
export const SVG_H = FIELD_H + FIELD_PAD.y * 2;

export const DEFAULT_VIEWBOX: ViewBox = { x: 0, y: 0, w: SVG_W, h: SVG_H };
export const DEFAULT_LINE_COLOR = '#facc15';
export const DEFAULT_LINE_WIDTH = 3;
export const DEFAULT_PLAYBACK_SPEED = 1;
export const BOARD_STORAGE_VERSION = 1;
export const HOME_TEAM_COLOR = '#2563eb';
export const AWAY_TEAM_COLOR = '#ef4444';

export const ZOOM_PRESETS: Array<{ id: string; label: string; viewBox: ViewBox }> = [
    { id: 'full', label: 'Campo', viewBox: { x: 0, y: 0, w: SVG_W, h: SVG_H } },
    { id: 'half', label: 'Mitad', viewBox: { x: 0, y: 250, w: SVG_W, h: 600 } },
    { id: '22attack', label: '22 Rival', viewBox: { x: 0, y: 0, w: SVG_W, h: 420 } },
    { id: '22defense', label: '22 Propio', viewBox: { x: 0, y: 680, w: SVG_W, h: 420 } },
    { id: '5m', label: '5m', viewBox: { x: 150, y: 400, w: 500, h: 300 } },
    { id: 'left', label: 'Izquierda', viewBox: { x: 0, y: 0, w: 450, h: SVG_H } },
    { id: 'right', label: 'Derecha', viewBox: { x: 350, y: 0, w: 450, h: SVG_H } },
];

export const GENERAL_ZOOM_PRESETS: Array<{ id: string; label: string; viewBox: ViewBox }> = [
    { id: 'full', label: 'Campo', viewBox: { x: 0, y: 0, w: SVG_W, h: SVG_H } },
    { id: 'top', label: 'Sector alto', viewBox: { x: 0, y: 0, w: SVG_W, h: 560 } },
    { id: 'middle', label: 'Centro', viewBox: { x: 120, y: 250, w: 560, h: 600 } },
    { id: 'bottom', label: 'Sector bajo', viewBox: { x: 0, y: 540, w: SVG_W, h: 560 } },
    { id: 'left', label: 'Izquierda', viewBox: { x: 0, y: 0, w: 450, h: SVG_H } },
    { id: 'right', label: 'Derecha', viewBox: { x: 350, y: 0, w: 450, h: SVG_H } },
];

export const RUGBY_PRESETS: RugbyPreset[] = [
    {
        id: 'scrum-center',
        name: 'Scrum centro',
        category: 'Scrum',
        players: [
            { id: 'h1', number: 1, x: 46, y: 62, team: 'home' },
            { id: 'h2', number: 2, x: 50, y: 62, team: 'home' },
            { id: 'h3', number: 3, x: 54, y: 62, team: 'home' },
            { id: 'h4', number: 4, x: 47, y: 58, team: 'home' },
            { id: 'h5', number: 5, x: 53, y: 58, team: 'home' },
            { id: 'h6', number: 6, x: 40, y: 59, team: 'home' },
            { id: 'h7', number: 7, x: 60, y: 59, team: 'home' },
            { id: 'h8', number: 8, x: 50, y: 55, team: 'home' },
            { id: 'h9', number: 9, x: 50, y: 48, team: 'home' },
            { id: 'h10', number: 10, x: 50, y: 38, team: 'home' },
            { id: 'h11', number: 11, x: 18, y: 32, team: 'home' },
            { id: 'h12', number: 12, x: 38, y: 30, team: 'home' },
            { id: 'h13', number: 13, x: 62, y: 30, team: 'home' },
            { id: 'h14', number: 14, x: 82, y: 32, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 20, team: 'home' },
        ],
        ball: { x: 50, y: 48, visible: true },
        lines: [],
        viewBox: { x: 0, y: 140, w: SVG_W, h: 760 },
    },
    {
        id: 'scrum-left',
        name: 'Scrum izquierdo',
        category: 'Scrum',
        players: [
            { id: 'h1', number: 1, x: 31, y: 62, team: 'home' },
            { id: 'h2', number: 2, x: 35, y: 62, team: 'home' },
            { id: 'h3', number: 3, x: 39, y: 62, team: 'home' },
            { id: 'h4', number: 4, x: 32, y: 58, team: 'home' },
            { id: 'h5', number: 5, x: 38, y: 58, team: 'home' },
            { id: 'h6', number: 6, x: 25, y: 59, team: 'home' },
            { id: 'h7', number: 7, x: 45, y: 59, team: 'home' },
            { id: 'h8', number: 8, x: 35, y: 55, team: 'home' },
            { id: 'h9', number: 9, x: 35, y: 48, team: 'home' },
            { id: 'h10', number: 10, x: 55, y: 38, team: 'home' },
            { id: 'h11', number: 11, x: 15, y: 32, team: 'home' },
            { id: 'h12', number: 12, x: 45, y: 30, team: 'home' },
            { id: 'h13', number: 13, x: 65, y: 30, team: 'home' },
            { id: 'h14', number: 14, x: 82, y: 32, team: 'home' },
            { id: 'h15', number: 15, x: 60, y: 20, team: 'home' },
        ],
        ball: { x: 35, y: 48, visible: true },
        lines: [],
        viewBox: { x: 0, y: 140, w: SVG_W, h: 760 },
    },
    {
        id: 'scrum-right',
        name: 'Scrum derecho',
        category: 'Scrum',
        players: [
            { id: 'h1', number: 1, x: 61, y: 62, team: 'home' },
            { id: 'h2', number: 2, x: 65, y: 62, team: 'home' },
            { id: 'h3', number: 3, x: 69, y: 62, team: 'home' },
            { id: 'h4', number: 4, x: 62, y: 58, team: 'home' },
            { id: 'h5', number: 5, x: 68, y: 58, team: 'home' },
            { id: 'h6', number: 6, x: 55, y: 59, team: 'home' },
            { id: 'h7', number: 7, x: 75, y: 59, team: 'home' },
            { id: 'h8', number: 8, x: 65, y: 55, team: 'home' },
            { id: 'h9', number: 9, x: 65, y: 48, team: 'home' },
            { id: 'h10', number: 10, x: 45, y: 38, team: 'home' },
            { id: 'h11', number: 11, x: 18, y: 32, team: 'home' },
            { id: 'h12', number: 12, x: 35, y: 30, team: 'home' },
            { id: 'h13', number: 13, x: 55, y: 30, team: 'home' },
            { id: 'h14', number: 14, x: 85, y: 32, team: 'home' },
            { id: 'h15', number: 15, x: 40, y: 20, team: 'home' },
        ],
        ball: { x: 65, y: 48, visible: true },
        lines: [],
        viewBox: { x: 0, y: 140, w: SVG_W, h: 760 },
    },
    {
        id: 'line-mid-5',
        name: 'Line mitad (5)',
        category: 'Line',
        players: [
            { id: 'h1', number: 1, x: 88, y: 48, team: 'home' },
            { id: 'h4', number: 4, x: 88, y: 44, team: 'home' },
            { id: 'h5', number: 5, x: 88, y: 40, team: 'home' },
            { id: 'h6', number: 6, x: 88, y: 36, team: 'home' },
            { id: 'h7', number: 7, x: 88, y: 32, team: 'home' },
            { id: 'h2', number: 2, x: 94, y: 42, team: 'home' },
            { id: 'h8', number: 8, x: 78, y: 42, team: 'home' },
            { id: 'h3', number: 3, x: 78, y: 38, team: 'home' },
            { id: 'h9', number: 9, x: 60, y: 32, team: 'home' },
            { id: 'h10', number: 10, x: 50, y: 26, team: 'home' },
            { id: 'h11', number: 11, x: 20, y: 22, team: 'home' },
            { id: 'h12', number: 12, x: 40, y: 20, team: 'home' },
            { id: 'h13', number: 13, x: 60, y: 20, team: 'home' },
            { id: 'h14', number: 14, x: 80, y: 22, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 14, team: 'home' },
        ],
        ball: { x: 94, y: 42, visible: true },
        lines: [],
        viewBox: { x: 0, y: 0, w: SVG_W, h: 600 },
    },
    {
        id: 'line-mid-7',
        name: 'Line mitad (7)',
        category: 'Line',
        players: [
            { id: 'h1', number: 1, x: 88, y: 50, team: 'home' },
            { id: 'h3', number: 3, x: 88, y: 46, team: 'home' },
            { id: 'h4', number: 4, x: 88, y: 42, team: 'home' },
            { id: 'h5', number: 5, x: 88, y: 38, team: 'home' },
            { id: 'h6', number: 6, x: 88, y: 34, team: 'home' },
            { id: 'h7', number: 7, x: 88, y: 30, team: 'home' },
            { id: 'h8', number: 8, x: 88, y: 26, team: 'home' },
            { id: 'h2', number: 2, x: 94, y: 40, team: 'home' },
            { id: 'h9', number: 9, x: 65, y: 32, team: 'home' },
            { id: 'h10', number: 10, x: 50, y: 26, team: 'home' },
            { id: 'h11', number: 11, x: 20, y: 22, team: 'home' },
            { id: 'h12', number: 12, x: 38, y: 20, team: 'home' },
            { id: 'h13', number: 13, x: 62, y: 20, team: 'home' },
            { id: 'h14', number: 14, x: 80, y: 22, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 14, team: 'home' },
        ],
        ball: { x: 94, y: 40, visible: true },
        lines: [],
        viewBox: { x: 0, y: 0, w: SVG_W, h: 600 },
    },
    {
        id: 'line-22-5',
        name: 'Line 22 (5)',
        category: 'Line',
        players: [
            { id: 'h1', number: 1, x: 88, y: 42, team: 'home' },
            { id: 'h4', number: 4, x: 88, y: 38, team: 'home' },
            { id: 'h5', number: 5, x: 88, y: 34, team: 'home' },
            { id: 'h6', number: 6, x: 88, y: 30, team: 'home' },
            { id: 'h7', number: 7, x: 88, y: 26, team: 'home' },
            { id: 'h2', number: 2, x: 94, y: 36, team: 'home' },
            { id: 'h8', number: 8, x: 78, y: 36, team: 'home' },
            { id: 'h3', number: 3, x: 78, y: 32, team: 'home' },
            { id: 'h9', number: 9, x: 60, y: 28, team: 'home' },
            { id: 'h10', number: 10, x: 50, y: 22, team: 'home' },
            { id: 'h11', number: 11, x: 20, y: 18, team: 'home' },
            { id: 'h12', number: 12, x: 38, y: 16, team: 'home' },
            { id: 'h13', number: 13, x: 62, y: 16, team: 'home' },
            { id: 'h14', number: 14, x: 80, y: 18, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 10, team: 'home' },
        ],
        ball: { x: 94, y: 36, visible: true },
        lines: [],
        viewBox: { x: 0, y: 0, w: SVG_W, h: 520 },
    },
    {
        id: 'line-22-7',
        name: 'Line 22 (7)',
        category: 'Line',
        players: [
            { id: 'h1', number: 1, x: 88, y: 44, team: 'home' },
            { id: 'h3', number: 3, x: 88, y: 40, team: 'home' },
            { id: 'h4', number: 4, x: 88, y: 36, team: 'home' },
            { id: 'h5', number: 5, x: 88, y: 32, team: 'home' },
            { id: 'h6', number: 6, x: 88, y: 28, team: 'home' },
            { id: 'h7', number: 7, x: 88, y: 24, team: 'home' },
            { id: 'h8', number: 8, x: 88, y: 20, team: 'home' },
            { id: 'h2', number: 2, x: 94, y: 34, team: 'home' },
            { id: 'h9', number: 9, x: 65, y: 28, team: 'home' },
            { id: 'h10', number: 10, x: 50, y: 22, team: 'home' },
            { id: 'h11', number: 11, x: 20, y: 18, team: 'home' },
            { id: 'h12', number: 12, x: 38, y: 16, team: 'home' },
            { id: 'h13', number: 13, x: 62, y: 16, team: 'home' },
            { id: 'h14', number: 14, x: 80, y: 18, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 10, team: 'home' },
        ],
        ball: { x: 94, y: 34, visible: true },
        lines: [],
        viewBox: { x: 0, y: 0, w: SVG_W, h: 520 },
    },
    {
        id: 'line-5m-5',
        name: 'Line 5m (5)',
        category: 'Line',
        players: [
            { id: 'h1', number: 1, x: 88, y: 36, team: 'home' },
            { id: 'h4', number: 4, x: 88, y: 32, team: 'home' },
            { id: 'h5', number: 5, x: 88, y: 28, team: 'home' },
            { id: 'h6', number: 6, x: 88, y: 24, team: 'home' },
            { id: 'h7', number: 7, x: 88, y: 20, team: 'home' },
            { id: 'h2', number: 2, x: 94, y: 30, team: 'home' },
            { id: 'h8', number: 8, x: 78, y: 30, team: 'home' },
            { id: 'h3', number: 3, x: 78, y: 26, team: 'home' },
            { id: 'h9', number: 9, x: 60, y: 22, team: 'home' },
            { id: 'h10', number: 10, x: 50, y: 16, team: 'home' },
            { id: 'h11', number: 11, x: 20, y: 12, team: 'home' },
            { id: 'h12', number: 12, x: 38, y: 10, team: 'home' },
            { id: 'h13', number: 13, x: 62, y: 10, team: 'home' },
            { id: 'h14', number: 14, x: 80, y: 12, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 6, team: 'home' },
        ],
        ball: { x: 94, y: 30, visible: true },
        lines: [],
        viewBox: { x: 0, y: 0, w: SVG_W, h: 460 },
    },
    {
        id: 'line-5m-7',
        name: 'Line 5m (7)',
        category: 'Line',
        players: [
            { id: 'h1', number: 1, x: 88, y: 38, team: 'home' },
            { id: 'h3', number: 3, x: 88, y: 34, team: 'home' },
            { id: 'h4', number: 4, x: 88, y: 30, team: 'home' },
            { id: 'h5', number: 5, x: 88, y: 26, team: 'home' },
            { id: 'h6', number: 6, x: 88, y: 22, team: 'home' },
            { id: 'h7', number: 7, x: 88, y: 18, team: 'home' },
            { id: 'h8', number: 8, x: 88, y: 14, team: 'home' },
            { id: 'h2', number: 2, x: 94, y: 28, team: 'home' },
            { id: 'h9', number: 9, x: 65, y: 22, team: 'home' },
            { id: 'h10', number: 10, x: 50, y: 16, team: 'home' },
            { id: 'h11', number: 11, x: 20, y: 12, team: 'home' },
            { id: 'h12', number: 12, x: 38, y: 10, team: 'home' },
            { id: 'h13', number: 13, x: 62, y: 10, team: 'home' },
            { id: 'h14', number: 14, x: 80, y: 12, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 6, team: 'home' },
        ],
        ball: { x: 94, y: 28, visible: true },
        lines: [],
        viewBox: { x: 0, y: 0, w: SVG_W, h: 460 },
    },
    {
        id: 'kickoff',
        name: 'Kickoff',
        category: 'Salidas',
        players: [
            { id: 'h1', number: 1, x: 30, y: 88, team: 'home' },
            { id: 'h2', number: 2, x: 45, y: 88, team: 'home' },
            { id: 'h3', number: 3, x: 60, y: 88, team: 'home' },
            { id: 'h4', number: 4, x: 35, y: 82, team: 'home' },
            { id: 'h5', number: 5, x: 55, y: 82, team: 'home' },
            { id: 'h6', number: 6, x: 25, y: 78, team: 'home' },
            { id: 'h7', number: 7, x: 65, y: 78, team: 'home' },
            { id: 'h8', number: 8, x: 50, y: 76, team: 'home' },
            { id: 'h9', number: 9, x: 50, y: 70, team: 'home' },
            { id: 'h10', number: 10, x: 50, y: 65, team: 'home' },
            { id: 'h11', number: 11, x: 20, y: 62, team: 'home' },
            { id: 'h12', number: 12, x: 40, y: 60, team: 'home' },
            { id: 'h13', number: 13, x: 60, y: 60, team: 'home' },
            { id: 'h14', number: 14, x: 80, y: 62, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 55, team: 'home' },
        ],
        ball: { x: 50, y: 88, visible: true },
        lines: [],
        viewBox: { x: 0, y: 440, w: SVG_W, h: 660 },
    },
    {
        id: 'reception',
        name: 'Recepcion salida',
        category: 'Salidas',
        players: [
            { id: 'h1', number: 1, x: 35, y: 75, team: 'home' },
            { id: 'h2', number: 2, x: 50, y: 78, team: 'home' },
            { id: 'h3', number: 3, x: 65, y: 75, team: 'home' },
            { id: 'h4', number: 4, x: 30, y: 68, team: 'home' },
            { id: 'h5', number: 5, x: 70, y: 68, team: 'home' },
            { id: 'h6', number: 6, x: 25, y: 60, team: 'home' },
            { id: 'h7', number: 7, x: 75, y: 60, team: 'home' },
            { id: 'h8', number: 8, x: 50, y: 58, team: 'home' },
            { id: 'h9', number: 9, x: 50, y: 50, team: 'home' },
            { id: 'h10', number: 10, x: 45, y: 45, team: 'home' },
            { id: 'h11', number: 11, x: 20, y: 42, team: 'home' },
            { id: 'h12', number: 12, x: 35, y: 38, team: 'home' },
            { id: 'h13', number: 13, x: 60, y: 38, team: 'home' },
            { id: 'h14', number: 14, x: 80, y: 42, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 32, team: 'home' },
        ],
        ball: { x: 50, y: 55, visible: true },
        lines: [],
        viewBox: { x: 0, y: 240, w: SVG_W, h: 660 },
    },
    {
        id: 'exit-22',
        name: 'Salida 22',
        category: '22',
        players: [
            { id: 'h1', number: 1, x: 30, y: 90, team: 'home' },
            { id: 'h2', number: 2, x: 50, y: 92, team: 'home' },
            { id: 'h3', number: 3, x: 70, y: 90, team: 'home' },
            { id: 'h4', number: 4, x: 35, y: 84, team: 'home' },
            { id: 'h5', number: 5, x: 65, y: 84, team: 'home' },
            { id: 'h6', number: 6, x: 25, y: 78, team: 'home' },
            { id: 'h7', number: 7, x: 75, y: 78, team: 'home' },
            { id: 'h8', number: 8, x: 50, y: 76, team: 'home' },
            { id: 'h9', number: 9, x: 50, y: 70, team: 'home' },
            { id: 'h10', number: 10, x: 50, y: 65, team: 'home' },
            { id: 'h11', number: 11, x: 20, y: 60, team: 'home' },
            { id: 'h12', number: 12, x: 40, y: 58, team: 'home' },
            { id: 'h13', number: 13, x: 60, y: 58, team: 'home' },
            { id: 'h14', number: 14, x: 80, y: 60, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 52, team: 'home' },
        ],
        ball: { x: 50, y: 92, visible: true },
        lines: [],
        viewBox: { x: 0, y: 420, w: SVG_W, h: 680 },
    },
    {
        id: 'penal-offense',
        name: 'Penal ofensivo',
        category: 'Penales',
        players: [
            { id: 'h1', number: 1, x: 30, y: 70, team: 'home' },
            { id: 'h2', number: 2, x: 45, y: 72, team: 'home' },
            { id: 'h3', number: 3, x: 60, y: 70, team: 'home' },
            { id: 'h4', number: 4, x: 35, y: 64, team: 'home' },
            { id: 'h5', number: 5, x: 55, y: 64, team: 'home' },
            { id: 'h6', number: 6, x: 25, y: 58, team: 'home' },
            { id: 'h7', number: 7, x: 65, y: 58, team: 'home' },
            { id: 'h8', number: 8, x: 50, y: 56, team: 'home' },
            { id: 'h9', number: 9, x: 50, y: 50, team: 'home' },
            { id: 'h10', number: 10, x: 50, y: 44, team: 'home' },
            { id: 'h11', number: 11, x: 20, y: 40, team: 'home' },
            { id: 'h12', number: 12, x: 38, y: 36, team: 'home' },
            { id: 'h13', number: 13, x: 62, y: 36, team: 'home' },
            { id: 'h14', number: 14, x: 80, y: 40, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 28, team: 'home' },
        ],
        ball: { x: 50, y: 50, visible: true },
        lines: [],
        viewBox: { x: 0, y: 180, w: SVG_W, h: 620 },
    },
    {
        id: 'free-kick',
        name: 'Free kick',
        category: 'Penales',
        players: [
            { id: 'h1', number: 1, x: 35, y: 65, team: 'home' },
            { id: 'h2', number: 2, x: 50, y: 68, team: 'home' },
            { id: 'h3', number: 3, x: 65, y: 65, team: 'home' },
            { id: 'h4', number: 4, x: 30, y: 58, team: 'home' },
            { id: 'h5', number: 5, x: 70, y: 58, team: 'home' },
            { id: 'h6', number: 6, x: 25, y: 52, team: 'home' },
            { id: 'h7', number: 7, x: 75, y: 52, team: 'home' },
            { id: 'h8', number: 8, x: 50, y: 50, team: 'home' },
            { id: 'h9', number: 9, x: 50, y: 44, team: 'home' },
            { id: 'h10', number: 10, x: 50, y: 38, team: 'home' },
            { id: 'h11', number: 11, x: 20, y: 34, team: 'home' },
            { id: 'h12', number: 12, x: 38, y: 30, team: 'home' },
            { id: 'h13', number: 13, x: 62, y: 30, team: 'home' },
            { id: 'h14', number: 14, x: 80, y: 34, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 24, team: 'home' },
        ],
        ball: { x: 50, y: 44, visible: true },
        lines: [],
        viewBox: { x: 0, y: 140, w: SVG_W, h: 620 },
    },
    {
        id: 'defense-22',
        name: 'Defensa 22',
        category: 'Defensa',
        players: [
            { id: 'h1', number: 1, x: 30, y: 88, team: 'home' },
            { id: 'h2', number: 2, x: 50, y: 90, team: 'home' },
            { id: 'h3', number: 3, x: 70, y: 88, team: 'home' },
            { id: 'h4', number: 4, x: 35, y: 82, team: 'home' },
            { id: 'h5', number: 5, x: 65, y: 82, team: 'home' },
            { id: 'h6', number: 6, x: 25, y: 76, team: 'home' },
            { id: 'h7', number: 7, x: 75, y: 76, team: 'home' },
            { id: 'h8', number: 8, x: 50, y: 74, team: 'home' },
            { id: 'h9', number: 9, x: 50, y: 68, team: 'home' },
            { id: 'h10', number: 10, x: 50, y: 62, team: 'home' },
            { id: 'h11', number: 11, x: 20, y: 58, team: 'home' },
            { id: 'h12', number: 12, x: 40, y: 56, team: 'home' },
            { id: 'h13', number: 13, x: 60, y: 56, team: 'home' },
            { id: 'h14', number: 14, x: 80, y: 58, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 50, team: 'home' },
        ],
        ball: { x: 50, y: 75, visible: true },
        lines: [],
        viewBox: { x: 0, y: 400, w: SVG_W, h: 700 },
    },
];

export const DEFAULT_FORMATIONS: Record<string, PlayerChip[]> = {
    rugby: [
        { id: 'h1', number: 1, x: 35, y: 82, team: 'home' },
        { id: 'h2', number: 2, x: 50, y: 85, team: 'home' },
        { id: 'h3', number: 3, x: 65, y: 82, team: 'home' },
        { id: 'h4', number: 4, x: 45, y: 72, team: 'home' },
        { id: 'h5', number: 5, x: 55, y: 72, team: 'home' },
        { id: 'h6', number: 6, x: 35, y: 65, team: 'home' },
        { id: 'h7', number: 7, x: 65, y: 65, team: 'home' },
        { id: 'h8', number: 8, x: 50, y: 62, team: 'home' },
        { id: 'h9', number: 9, x: 50, y: 55, team: 'home' },
        { id: 'h10', number: 10, x: 50, y: 48, team: 'home' },
        { id: 'h11', number: 11, x: 25, y: 35, team: 'home' },
        { id: 'h12', number: 12, x: 40, y: 40, team: 'home' },
        { id: 'h13', number: 13, x: 60, y: 40, team: 'home' },
        { id: 'h14', number: 14, x: 75, y: 35, team: 'home' },
        { id: 'h15', number: 15, x: 50, y: 22, team: 'home' },
    ],
    football: [
        { id: 'h1', number: 1, x: 50, y: 90, team: 'home' },
        { id: 'h2', number: 2, x: 20, y: 78, team: 'home' },
        { id: 'h3', number: 4, x: 40, y: 80, team: 'home' },
        { id: 'h4', number: 5, x: 60, y: 80, team: 'home' },
        { id: 'h5', number: 3, x: 80, y: 78, team: 'home' },
        { id: 'h6', number: 8, x: 50, y: 62, team: 'home' },
        { id: 'h7', number: 6, x: 25, y: 55, team: 'home' },
        { id: 'h8', number: 7, x: 75, y: 55, team: 'home' },
        { id: 'h9', number: 10, x: 50, y: 45, team: 'home' },
        { id: 'h10', number: 11, x: 35, y: 35, team: 'home' },
        { id: 'h11', number: 9, x: 65, y: 35, team: 'home' },
    ],
    basketball: [
        { id: 'h1', number: 1, x: 20, y: 80, team: 'home' },
        { id: 'h2', number: 2, x: 50, y: 75, team: 'home' },
        { id: 'h3', number: 3, x: 80, y: 80, team: 'home' },
        { id: 'h4', number: 4, x: 35, y: 55, team: 'home' },
        { id: 'h5', number: 5, x: 65, y: 55, team: 'home' },
    ],
    hockey: [
        { id: 'h1', number: 1, x: 50, y: 88, team: 'home' },
        { id: 'h2', number: 2, x: 25, y: 75, team: 'home' },
        { id: 'h3', number: 3, x: 50, y: 70, team: 'home' },
        { id: 'h4', number: 4, x: 75, y: 75, team: 'home' },
        { id: 'h5', number: 5, x: 35, y: 58, team: 'home' },
        { id: 'h6', number: 6, x: 65, y: 58, team: 'home' },
        { id: 'h7', number: 7, x: 50, y: 50, team: 'home' },
        { id: 'h8', number: 8, x: 35, y: 38, team: 'home' },
        { id: 'h9', number: 9, x: 65, y: 38, team: 'home' },
        { id: 'h10', number: 10, x: 45, y: 25, team: 'home' },
        { id: 'h11', number: 11, x: 55, y: 25, team: 'home' },
    ],
};

export const DEFAULT_BALL = { x: 50, y: 55, visible: true };
export const DRAW_COLORS = ['#facc15', '#ef4444', '#3b82f6', '#22c55e', '#ffffff', '#f97316', '#a855f7'];
export const PLAYBACK_SPEEDS = [0.25, 0.5, 0.75, 1, 1.25, 1.5, 2];
export const FRAME_THUMB = {
    padX: 10,
    padY: 10,
    width: 72,
    height: 118,
    svgWidth: 92,
    svgHeight: 138,
};
