import type { ViewBox, RugbyPreset, PlayerChip } from './types';

export const FIELD_PAD = { x: 50, y: 50 };
export const FIELD_W = 700;
export const FIELD_H = 1000;
export const SVG_W = FIELD_W + FIELD_PAD.x * 2;
export const SVG_H = FIELD_H + FIELD_PAD.y * 2;

export const DEFAULT_VIEWBOX: ViewBox = { x: 0, y: 0, w: SVG_W, h: SVG_H };
export const DEFAULT_LINE_COLOR = '#facc15';
export const DEFAULT_LINE_WIDTH = 3;
export const DEFAULT_PLAYBACK_SPEED = 1;
export const BOARD_STORAGE_VERSION = 1;
export const HOME_TEAM_COLOR = '#2563eb';
export const AWAY_TEAM_COLOR = '#ef4444';

export const ZOOM_PRESETS: Array<{ id: string; label: string; viewBox: ViewBox }> = [
    { id: 'full', label: 'Campo', viewBox: { x: 0, y: 0, w: SVG_W, h: SVG_H } },
    { id: 'half', label: 'Mitad', viewBox: { x: 0, y: 250, w: SVG_W, h: 600 } },
    { id: '22attack', label: '22 Rival', viewBox: { x: 0, y: 0, w: SVG_W, h: 420 } },
    { id: '22defense', label: '22 Propio', viewBox: { x: 0, y: 680, w: SVG_W, h: 420 } },
    { id: '5m', label: '5m', viewBox: { x: 150, y: 400, w: 500, h: 300 } },
    { id: 'left', label: 'Izquierda', viewBox: { x: 0, y: 0, w: 450, h: SVG_H } },
    { id: 'right', label: 'Derecha', viewBox: { x: 350, y: 0, w: 450, h: SVG_H } },
];

export const GENERAL_ZOOM_PRESETS: Array<{ id: string; label: string; viewBox: ViewBox }> = [
    { id: 'full', label: 'Campo', viewBox: { x: 0, y: 0, w: SVG_W, h: SVG_H } },
    { id: 'top', label: 'Sector alto', viewBox: { x: 0, y: 0, w: SVG_W, h: 560 } },
    { id: 'middle', label: 'Centro', viewBox: { x: 120, y: 250, w: 560, h: 600 } },
    { id: 'bottom', label: 'Sector bajo', viewBox: { x: 0, y: 540, w: SVG_W, h: 560 } },
    { id: 'left', label: 'Izquierda', viewBox: { x: 0, y: 0, w: 450, h: SVG_H } },
    { id: 'right', label: 'Derecha', viewBox: { x: 350, y: 0, w: 450, h: SVG_H } },
];

/**
 * Convencion: HOME ataca hacia y=0 (try line rival arriba), defiende en y~89 (try line propio abajo).
 * - 22 propio: y=72 | mitad: y=50 | 22 rival: y=28 | 5m rival: y=18
 * - En scrum y maul el front row lidera el empuje (y mas bajo); locks y back row empujan detras (y mas alto).
 * - En line-out la fila de saltadores es PERPENDICULAR a la touchline (varia x, misma y).
 * - El 15 (FB) es siempre el mas profundo del cuadro defensivo.
 */
export const RUGBY_PRESETS: RugbyPreset[] = [
    {
        id: 'scrum-center',
        name: 'Scrum centro',
        category: 'Scrum',
        players: [
            // Primera linea pegada a la linea de contacto (y=50), pack extendido en propio campo.
            { id: 'h1', number: 1, x: 46, y: 49, team: 'home' },
            { id: 'h2', number: 2, x: 50, y: 49, team: 'home' },
            { id: 'h3', number: 3, x: 54, y: 49, team: 'home' },
            { id: 'h4', number: 4, x: 47, y: 52, team: 'home' },
            { id: 'h5', number: 5, x: 53, y: 52, team: 'home' },
            { id: 'h6', number: 6, x: 42, y: 52, team: 'home' },
            { id: 'h7', number: 7, x: 58, y: 52, team: 'home' },
            { id: 'h8', number: 8, x: 50, y: 55, team: 'home' },
            { id: 'h9', number: 9, x: 56, y: 55, team: 'home' },
            { id: 'h10', number: 10, x: 60, y: 62, team: 'home' },
            { id: 'h12', number: 12, x: 48, y: 68, team: 'home' },
            { id: 'h13', number: 13, x: 66, y: 68, team: 'home' },
            { id: 'h11', number: 11, x: 14, y: 72, team: 'home' },
            { id: 'h14', number: 14, x: 88, y: 70, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 84, team: 'home' },
        ],
        ball: { x: 56, y: 55, visible: true },
        lines: [],
        viewBox: { x: 0, y: 250, w: SVG_W, h: 800 },
    },
    {
        id: 'scrum-left',
        name: 'Scrum izquierdo',
        category: 'Scrum',
        players: [
            // Scrum sobre canal izquierdo: lado ciego = izquierda, lado abierto = derecha.
            { id: 'h1', number: 1, x: 31, y: 49, team: 'home' },
            { id: 'h2', number: 2, x: 35, y: 49, team: 'home' },
            { id: 'h3', number: 3, x: 39, y: 49, team: 'home' },
            { id: 'h4', number: 4, x: 32, y: 52, team: 'home' },
            { id: 'h5', number: 5, x: 38, y: 52, team: 'home' },
            { id: 'h6', number: 6, x: 27, y: 52, team: 'home' },
            { id: 'h7', number: 7, x: 43, y: 52, team: 'home' },
            { id: 'h8', number: 8, x: 35, y: 55, team: 'home' },
            { id: 'h9', number: 9, x: 42, y: 55, team: 'home' },
            { id: 'h10', number: 10, x: 52, y: 62, team: 'home' },
            { id: 'h12', number: 12, x: 44, y: 68, team: 'home' },
            { id: 'h13', number: 13, x: 62, y: 68, team: 'home' },
            { id: 'h14', number: 14, x: 86, y: 70, team: 'home' },
            { id: 'h11', number: 11, x: 10, y: 64, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 84, team: 'home' },
        ],
        ball: { x: 42, y: 55, visible: true },
        lines: [],
        viewBox: { x: 0, y: 250, w: SVG_W, h: 800 },
    },
    {
        id: 'scrum-right',
        name: 'Scrum derecho',
        category: 'Scrum',
        players: [
            // Scrum sobre canal derecho: lado ciego = derecha, lado abierto = izquierda.
            { id: 'h1', number: 1, x: 61, y: 49, team: 'home' },
            { id: 'h2', number: 2, x: 65, y: 49, team: 'home' },
            { id: 'h3', number: 3, x: 69, y: 49, team: 'home' },
            { id: 'h4', number: 4, x: 62, y: 52, team: 'home' },
            { id: 'h5', number: 5, x: 68, y: 52, team: 'home' },
            { id: 'h6', number: 6, x: 73, y: 52, team: 'home' },
            { id: 'h7', number: 7, x: 57, y: 52, team: 'home' },
            { id: 'h8', number: 8, x: 65, y: 55, team: 'home' },
            { id: 'h9', number: 9, x: 58, y: 55, team: 'home' },
            { id: 'h10', number: 10, x: 48, y: 62, team: 'home' },
            { id: 'h12', number: 12, x: 36, y: 68, team: 'home' },
            { id: 'h13', number: 13, x: 54, y: 68, team: 'home' },
            { id: 'h11', number: 11, x: 14, y: 70, team: 'home' },
            { id: 'h14', number: 14, x: 90, y: 64, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 84, team: 'home' },
        ],
        ball: { x: 58, y: 55, visible: true },
        lines: [],
        viewBox: { x: 0, y: 250, w: SVG_W, h: 800 },
    },
    {
        id: 'line-mid-5',
        name: 'Line mitad (5)',
        category: 'Line',
        players: [
            // Linea de touch en y=50; home se forma en y=49 (su lado), perpendicular a la touchline derecha.
            { id: 'h2', number: 2, x: 98, y: 49, team: 'home' },
            { id: 'h6', number: 6, x: 92, y: 49, team: 'home' },
            { id: 'h4', number: 4, x: 87, y: 49, team: 'home' },
            { id: 'h5', number: 5, x: 82, y: 49, team: 'home' },
            { id: 'h7', number: 7, x: 77, y: 49, team: 'home' },
            { id: 'h8', number: 8, x: 72, y: 49, team: 'home' },
            // Pilares apoyando los lifts de la linea.
            { id: 'h1', number: 1, x: 90, y: 52, team: 'home' },
            { id: 'h3', number: 3, x: 75, y: 52, team: 'home' },
            // 9 al fondo del line para extraer; backs distribuidos en propio campo.
            { id: 'h9', number: 9, x: 68, y: 53, team: 'home' },
            { id: 'h10', number: 10, x: 62, y: 60, team: 'home' },
            { id: 'h12', number: 12, x: 50, y: 64, team: 'home' },
            { id: 'h13', number: 13, x: 36, y: 64, team: 'home' },
            { id: 'h11', number: 11, x: 16, y: 68, team: 'home' },
            { id: 'h14', number: 14, x: 92, y: 60, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 80, team: 'home' },
        ],
        ball: { x: 98, y: 49, visible: true },
        lines: [],
        viewBox: { x: 0, y: 250, w: SVG_W, h: 800 },
    },
    {
        id: 'line-mid-7',
        name: 'Line mitad (7)',
        category: 'Line',
        players: [
            { id: 'h2', number: 2, x: 98, y: 49, team: 'home' },
            { id: 'h6', number: 6, x: 93, y: 49, team: 'home' },
            { id: 'h4', number: 4, x: 89, y: 49, team: 'home' },
            { id: 'h5', number: 5, x: 85, y: 49, team: 'home' },
            { id: 'h8', number: 8, x: 81, y: 49, team: 'home' },
            { id: 'h7', number: 7, x: 77, y: 49, team: 'home' },
            { id: 'h3', number: 3, x: 73, y: 49, team: 'home' },
            { id: 'h1', number: 1, x: 69, y: 49, team: 'home' },
            { id: 'h9', number: 9, x: 64, y: 53, team: 'home' },
            { id: 'h10', number: 10, x: 58, y: 60, team: 'home' },
            { id: 'h12', number: 12, x: 46, y: 64, team: 'home' },
            { id: 'h13', number: 13, x: 32, y: 64, team: 'home' },
            { id: 'h11', number: 11, x: 14, y: 68, team: 'home' },
            { id: 'h14', number: 14, x: 92, y: 60, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 80, team: 'home' },
        ],
        ball: { x: 98, y: 49, visible: true },
        lines: [],
        viewBox: { x: 0, y: 250, w: SVG_W, h: 800 },
    },
    {
        id: 'line-22-5',
        name: 'Line 22 rival (5)',
        category: 'Line',
        players: [
            // Linea de touch en y=28. Home (con throw) en y=27, rival enfrentado en y=29.
            { id: 'h2', number: 2, x: 98, y: 27, team: 'home' },
            { id: 'h6', number: 6, x: 92, y: 27, team: 'home' },
            { id: 'h4', number: 4, x: 87, y: 27, team: 'home' },
            { id: 'h5', number: 5, x: 82, y: 27, team: 'home' },
            { id: 'h7', number: 7, x: 77, y: 27, team: 'home' },
            { id: 'h8', number: 8, x: 72, y: 27, team: 'home' },
            { id: 'h1', number: 1, x: 90, y: 30, team: 'home' },
            { id: 'h3', number: 3, x: 75, y: 30, team: 'home' },
            { id: 'h9', number: 9, x: 68, y: 31, team: 'home' },
            { id: 'h10', number: 10, x: 62, y: 38, team: 'home' },
            { id: 'h12', number: 12, x: 50, y: 42, team: 'home' },
            { id: 'h13', number: 13, x: 36, y: 42, team: 'home' },
            { id: 'h11', number: 11, x: 16, y: 46, team: 'home' },
            { id: 'h14', number: 14, x: 92, y: 38, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 60, team: 'home' },
            // Rival enfrentado: line en y=29, backs replegados hacia su try.
            { id: 'a2', number: 2, x: 98, y: 29, team: 'away' },
            { id: 'a6', number: 6, x: 92, y: 29, team: 'away' },
            { id: 'a4', number: 4, x: 87, y: 29, team: 'away' },
            { id: 'a5', number: 5, x: 82, y: 29, team: 'away' },
            { id: 'a7', number: 7, x: 77, y: 29, team: 'away' },
            { id: 'a8', number: 8, x: 72, y: 29, team: 'away' },
            { id: 'a1', number: 1, x: 90, y: 26, team: 'away' },
            { id: 'a3', number: 3, x: 75, y: 26, team: 'away' },
            { id: 'a9', number: 9, x: 68, y: 25, team: 'away' },
            { id: 'a10', number: 10, x: 62, y: 18, team: 'away' },
            { id: 'a12', number: 12, x: 50, y: 14, team: 'away' },
            { id: 'a13', number: 13, x: 36, y: 14, team: 'away' },
            { id: 'a11', number: 11, x: 16, y: 14, team: 'away' },
            { id: 'a14', number: 14, x: 92, y: 18, team: 'away' },
            { id: 'a15', number: 15, x: 50, y: 6, team: 'away' },
        ],
        ball: { x: 98, y: 27, visible: true },
        lines: [],
        viewBox: { x: 0, y: 0, w: SVG_W, h: 750 },
    },
    {
        id: 'line-22-7',
        name: 'Line 22 rival (7)',
        category: 'Line',
        players: [
            { id: 'h2', number: 2, x: 98, y: 27, team: 'home' },
            { id: 'h6', number: 6, x: 93, y: 27, team: 'home' },
            { id: 'h4', number: 4, x: 89, y: 27, team: 'home' },
            { id: 'h5', number: 5, x: 85, y: 27, team: 'home' },
            { id: 'h8', number: 8, x: 81, y: 27, team: 'home' },
            { id: 'h7', number: 7, x: 77, y: 27, team: 'home' },
            { id: 'h3', number: 3, x: 73, y: 27, team: 'home' },
            { id: 'h1', number: 1, x: 69, y: 27, team: 'home' },
            { id: 'h9', number: 9, x: 64, y: 31, team: 'home' },
            { id: 'h10', number: 10, x: 58, y: 38, team: 'home' },
            { id: 'h12', number: 12, x: 46, y: 42, team: 'home' },
            { id: 'h13', number: 13, x: 32, y: 42, team: 'home' },
            { id: 'h11', number: 11, x: 14, y: 46, team: 'home' },
            { id: 'h14', number: 14, x: 92, y: 38, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 60, team: 'home' },
            // Rival enfrentado en y=29 con line completa.
            { id: 'a2', number: 2, x: 98, y: 29, team: 'away' },
            { id: 'a6', number: 6, x: 93, y: 29, team: 'away' },
            { id: 'a4', number: 4, x: 89, y: 29, team: 'away' },
            { id: 'a5', number: 5, x: 85, y: 29, team: 'away' },
            { id: 'a8', number: 8, x: 81, y: 29, team: 'away' },
            { id: 'a7', number: 7, x: 77, y: 29, team: 'away' },
            { id: 'a3', number: 3, x: 73, y: 29, team: 'away' },
            { id: 'a1', number: 1, x: 69, y: 29, team: 'away' },
            { id: 'a9', number: 9, x: 64, y: 25, team: 'away' },
            { id: 'a10', number: 10, x: 58, y: 18, team: 'away' },
            { id: 'a12', number: 12, x: 46, y: 14, team: 'away' },
            { id: 'a13', number: 13, x: 32, y: 14, team: 'away' },
            { id: 'a11', number: 11, x: 14, y: 14, team: 'away' },
            { id: 'a14', number: 14, x: 92, y: 18, team: 'away' },
            { id: 'a15', number: 15, x: 50, y: 6, team: 'away' },
        ],
        ball: { x: 98, y: 27, visible: true },
        lines: [],
        viewBox: { x: 0, y: 0, w: SVG_W, h: 750 },
    },
    {
        id: 'line-5m-5',
        name: 'Line 5m rival (5)',
        category: 'Line',
        players: [
            // Linea de touch a 5m del try rival (y=18); home en y=17, rival enfrentado en y=19.
            { id: 'h2', number: 2, x: 98, y: 17, team: 'home' },
            { id: 'h6', number: 6, x: 92, y: 17, team: 'home' },
            { id: 'h4', number: 4, x: 87, y: 17, team: 'home' },
            { id: 'h5', number: 5, x: 82, y: 17, team: 'home' },
            { id: 'h7', number: 7, x: 77, y: 17, team: 'home' },
            { id: 'h8', number: 8, x: 72, y: 17, team: 'home' },
            { id: 'h1', number: 1, x: 90, y: 20, team: 'home' },
            { id: 'h3', number: 3, x: 75, y: 20, team: 'home' },
            { id: 'h9', number: 9, x: 68, y: 21, team: 'home' },
            { id: 'h10', number: 10, x: 60, y: 26, team: 'home' },
            { id: 'h12', number: 12, x: 48, y: 30, team: 'home' },
            { id: 'h13', number: 13, x: 34, y: 30, team: 'home' },
            { id: 'h11', number: 11, x: 16, y: 34, team: 'home' },
            { id: 'h14', number: 14, x: 92, y: 26, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 48, team: 'home' },
            // Rival defendiendo el try, enfrentado a 1m del line, backs en in-goal o cerca del try.
            { id: 'a2', number: 2, x: 98, y: 19, team: 'away' },
            { id: 'a6', number: 6, x: 92, y: 19, team: 'away' },
            { id: 'a4', number: 4, x: 87, y: 19, team: 'away' },
            { id: 'a5', number: 5, x: 82, y: 19, team: 'away' },
            { id: 'a7', number: 7, x: 77, y: 19, team: 'away' },
            { id: 'a8', number: 8, x: 72, y: 19, team: 'away' },
            { id: 'a1', number: 1, x: 90, y: 16, team: 'away' },
            { id: 'a3', number: 3, x: 75, y: 16, team: 'away' },
            { id: 'a9', number: 9, x: 68, y: 15, team: 'away' },
            { id: 'a10', number: 10, x: 60, y: 10, team: 'away' },
            { id: 'a12', number: 12, x: 48, y: 8, team: 'away' },
            { id: 'a13', number: 13, x: 34, y: 8, team: 'away' },
            { id: 'a11', number: 11, x: 16, y: 8, team: 'away' },
            { id: 'a14', number: 14, x: 92, y: 10, team: 'away' },
            { id: 'a15', number: 15, x: 50, y: 4, team: 'away' },
        ],
        ball: { x: 98, y: 17, visible: true },
        lines: [],
        viewBox: { x: 0, y: 0, w: SVG_W, h: 650 },
    },
    {
        id: 'line-5m-7',
        name: 'Line 5m rival (7)',
        category: 'Line',
        players: [
            { id: 'h2', number: 2, x: 98, y: 17, team: 'home' },
            { id: 'h6', number: 6, x: 93, y: 17, team: 'home' },
            { id: 'h4', number: 4, x: 89, y: 17, team: 'home' },
            { id: 'h5', number: 5, x: 85, y: 17, team: 'home' },
            { id: 'h8', number: 8, x: 81, y: 17, team: 'home' },
            { id: 'h7', number: 7, x: 77, y: 17, team: 'home' },
            { id: 'h3', number: 3, x: 73, y: 17, team: 'home' },
            { id: 'h1', number: 1, x: 69, y: 17, team: 'home' },
            { id: 'h9', number: 9, x: 64, y: 21, team: 'home' },
            { id: 'h10', number: 10, x: 56, y: 26, team: 'home' },
            { id: 'h12', number: 12, x: 44, y: 30, team: 'home' },
            { id: 'h13', number: 13, x: 30, y: 30, team: 'home' },
            { id: 'h11', number: 11, x: 14, y: 34, team: 'home' },
            { id: 'h14', number: 14, x: 92, y: 26, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 48, team: 'home' },
            // Rival defendiendo el line a 5m de su propio try.
            { id: 'a2', number: 2, x: 98, y: 19, team: 'away' },
            { id: 'a6', number: 6, x: 93, y: 19, team: 'away' },
            { id: 'a4', number: 4, x: 89, y: 19, team: 'away' },
            { id: 'a5', number: 5, x: 85, y: 19, team: 'away' },
            { id: 'a8', number: 8, x: 81, y: 19, team: 'away' },
            { id: 'a7', number: 7, x: 77, y: 19, team: 'away' },
            { id: 'a3', number: 3, x: 73, y: 19, team: 'away' },
            { id: 'a1', number: 1, x: 69, y: 19, team: 'away' },
            { id: 'a9', number: 9, x: 64, y: 15, team: 'away' },
            { id: 'a10', number: 10, x: 56, y: 10, team: 'away' },
            { id: 'a12', number: 12, x: 44, y: 8, team: 'away' },
            { id: 'a13', number: 13, x: 30, y: 8, team: 'away' },
            { id: 'a11', number: 11, x: 14, y: 8, team: 'away' },
            { id: 'a14', number: 14, x: 92, y: 10, team: 'away' },
            { id: 'a15', number: 15, x: 50, y: 4, team: 'away' },
        ],
        ball: { x: 98, y: 17, visible: true },
        lines: [],
        viewBox: { x: 0, y: 0, w: SVG_W, h: 650 },
    },
    {
        id: 'kickoff',
        name: 'Kickoff (saque desde mitad)',
        category: 'Salidas',
        players: [
            // Pelota sobre la linea de mitad (y=50). Pateador apenas detras (y=51) en propio campo.
            { id: 'h10', number: 10, x: 48, y: 51, team: 'home' },
            // Forwards en linea de chase ~5m detras del pateador.
            { id: 'h6', number: 6, x: 12, y: 55, team: 'home' },
            { id: 'h4', number: 4, x: 22, y: 55, team: 'home' },
            { id: 'h1', number: 1, x: 32, y: 55, team: 'home' },
            { id: 'h2', number: 2, x: 42, y: 55, team: 'home' },
            { id: 'h3', number: 3, x: 58, y: 55, team: 'home' },
            { id: 'h5', number: 5, x: 68, y: 55, team: 'home' },
            { id: 'h7', number: 7, x: 78, y: 55, team: 'home' },
            { id: 'h8', number: 8, x: 88, y: 55, team: 'home' },
            // 9 detras del pateador y backs en cobertura por capas.
            { id: 'h9', number: 9, x: 52, y: 62, team: 'home' },
            { id: 'h12', number: 12, x: 28, y: 68, team: 'home' },
            { id: 'h13', number: 13, x: 72, y: 68, team: 'home' },
            { id: 'h11', number: 11, x: 14, y: 76, team: 'home' },
            { id: 'h14', number: 14, x: 86, y: 76, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 86, team: 'home' },
            // Equipo receptor sobre la linea punteada de los 10m rival (y=42), espejando la formacion.
            { id: 'a6', number: 6, x: 12, y: 42, team: 'away' },
            { id: 'a4', number: 4, x: 22, y: 42, team: 'away' },
            { id: 'a1', number: 1, x: 32, y: 42, team: 'away' },
            { id: 'a2', number: 2, x: 42, y: 42, team: 'away' },
            { id: 'a3', number: 3, x: 58, y: 42, team: 'away' },
            { id: 'a5', number: 5, x: 68, y: 42, team: 'away' },
            { id: 'a7', number: 7, x: 78, y: 42, team: 'away' },
            { id: 'a8', number: 8, x: 88, y: 42, team: 'away' },
            { id: 'a9', number: 9, x: 50, y: 36, team: 'away' },
            { id: 'a10', number: 10, x: 50, y: 30, team: 'away' },
            { id: 'a12', number: 12, x: 30, y: 28, team: 'away' },
            { id: 'a13', number: 13, x: 70, y: 28, team: 'away' },
            { id: 'a11', number: 11, x: 14, y: 22, team: 'away' },
            { id: 'a14', number: 14, x: 86, y: 22, team: 'away' },
            { id: 'a15', number: 15, x: 50, y: 12, team: 'away' },
        ],
        ball: { x: 48, y: 50, visible: true },
        lines: [],
        viewBox: { x: 0, y: 0, w: SVG_W, h: SVG_H },
    },
    {
        id: 'reception',
        name: 'Recepcion salida',
        category: 'Salidas',
        players: [
            // Pods de recepcion: izquierdo (h6+h4), central (h2+h8), derecho (h5+h7) sobre los 10m propios.
            { id: 'h6', number: 6, x: 24, y: 60, team: 'home' },
            { id: 'h4', number: 4, x: 30, y: 62, team: 'home' },
            { id: 'h2', number: 2, x: 48, y: 60, team: 'home' },
            { id: 'h8', number: 8, x: 52, y: 62, team: 'home' },
            { id: 'h5', number: 5, x: 70, y: 62, team: 'home' },
            { id: 'h7', number: 7, x: 76, y: 60, team: 'home' },
            // Pilares como lifters atras de cada pod.
            { id: 'h1', number: 1, x: 27, y: 66, team: 'home' },
            { id: 'h3', number: 3, x: 73, y: 66, team: 'home' },
            // 9 sweeper, 10 organizando en bolsillo, centros adelantados de los wings.
            { id: 'h9', number: 9, x: 50, y: 70, team: 'home' },
            { id: 'h10', number: 10, x: 50, y: 76, team: 'home' },
            { id: 'h12', number: 12, x: 35, y: 72, team: 'home' },
            { id: 'h13', number: 13, x: 65, y: 72, team: 'home' },
            { id: 'h11', number: 11, x: 14, y: 68, team: 'home' },
            { id: 'h14', number: 14, x: 86, y: 68, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 86, team: 'home' },
        ],
        // Pelota cayendo en el pod central tras la salida rival.
        ball: { x: 50, y: 60, visible: true },
        lines: [],
        viewBox: { x: 0, y: 300, w: SVG_W, h: 780 },
    },
    {
        id: 'exit-22',
        name: 'Salida 22 (drop-out propio)',
        category: '22',
        players: [
            // Pelota en linea de 22 propia (y=72) lista para drop-kick.
            { id: 'h10', number: 10, x: 50, y: 73, team: 'home' },
            // Linea de chase delante del pateador (offside line en la pelota).
            { id: 'h1', number: 1, x: 16, y: 72, team: 'home' },
            { id: 'h6', number: 6, x: 26, y: 72, team: 'home' },
            { id: 'h4', number: 4, x: 36, y: 72, team: 'home' },
            { id: 'h2', number: 2, x: 44, y: 72, team: 'home' },
            { id: 'h5', number: 5, x: 56, y: 72, team: 'home' },
            { id: 'h3', number: 3, x: 64, y: 72, team: 'home' },
            { id: 'h7', number: 7, x: 74, y: 72, team: 'home' },
            { id: 'h8', number: 8, x: 84, y: 72, team: 'home' },
            // 9 al lado del pateador, backs replegados como segunda red.
            { id: 'h9', number: 9, x: 56, y: 75, team: 'home' },
            { id: 'h12', number: 12, x: 30, y: 80, team: 'home' },
            { id: 'h13', number: 13, x: 70, y: 80, team: 'home' },
            { id: 'h11', number: 11, x: 14, y: 84, team: 'home' },
            { id: 'h14', number: 14, x: 86, y: 84, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 88, team: 'home' },
            // Rival presionando justo al borde del 22 (linea de presion en y=70), backs cubriendo.
            { id: 'a1', number: 1, x: 16, y: 70, team: 'away' },
            { id: 'a6', number: 6, x: 26, y: 70, team: 'away' },
            { id: 'a4', number: 4, x: 36, y: 70, team: 'away' },
            { id: 'a2', number: 2, x: 44, y: 70, team: 'away' },
            { id: 'a5', number: 5, x: 56, y: 70, team: 'away' },
            { id: 'a3', number: 3, x: 64, y: 70, team: 'away' },
            { id: 'a7', number: 7, x: 74, y: 70, team: 'away' },
            { id: 'a8', number: 8, x: 84, y: 70, team: 'away' },
            { id: 'a9', number: 9, x: 44, y: 67, team: 'away' },
            { id: 'a10', number: 10, x: 50, y: 62, team: 'away' },
            { id: 'a12', number: 12, x: 30, y: 58, team: 'away' },
            { id: 'a13', number: 13, x: 70, y: 58, team: 'away' },
            { id: 'a11', number: 11, x: 14, y: 54, team: 'away' },
            { id: 'a14', number: 14, x: 86, y: 54, team: 'away' },
            { id: 'a15', number: 15, x: 50, y: 46, team: 'away' },
        ],
        ball: { x: 50, y: 72, visible: true },
        lines: [],
        viewBox: { x: 0, y: 350, w: SVG_W, h: 750 },
    },
    {
        id: 'penal-offense',
        name: 'Penal ofensivo',
        category: 'Penales',
        players: [
            // Marca del penal a la altura del 22 rival (y=28). Pelota con el 9 lista para tap o pateo.
            // Cuadro forward listo para empuje cerca de la marca, sin pisar la linea de off-side.
            { id: 'h1', number: 1, x: 36, y: 30, team: 'home' },
            { id: 'h2', number: 2, x: 44, y: 30, team: 'home' },
            { id: 'h3', number: 3, x: 52, y: 30, team: 'home' },
            { id: 'h4', number: 4, x: 38, y: 33, team: 'home' },
            { id: 'h5', number: 5, x: 50, y: 33, team: 'home' },
            { id: 'h6', number: 6, x: 30, y: 33, team: 'home' },
            { id: 'h7', number: 7, x: 58, y: 33, team: 'home' },
            { id: 'h8', number: 8, x: 44, y: 36, team: 'home' },
            // 9 sobre la marca, 10 abriendo el lado largo.
            { id: 'h9', number: 9, x: 50, y: 30, team: 'home' },
            { id: 'h10', number: 10, x: 60, y: 38, team: 'home' },
            { id: 'h12', number: 12, x: 50, y: 44, team: 'home' },
            { id: 'h13', number: 13, x: 70, y: 44, team: 'home' },
            { id: 'h11', number: 11, x: 18, y: 48, team: 'home' },
            { id: 'h14', number: 14, x: 88, y: 48, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 64, team: 'home' },
            // Rival respetando los 10m de la marca (linea de off-side en y=18) y backs profundos.
            { id: 'a1', number: 1, x: 36, y: 18, team: 'away' },
            { id: 'a2', number: 2, x: 44, y: 18, team: 'away' },
            { id: 'a3', number: 3, x: 52, y: 18, team: 'away' },
            { id: 'a4', number: 4, x: 30, y: 18, team: 'away' },
            { id: 'a5', number: 5, x: 58, y: 18, team: 'away' },
            { id: 'a6', number: 6, x: 22, y: 18, team: 'away' },
            { id: 'a7', number: 7, x: 66, y: 18, team: 'away' },
            { id: 'a8', number: 8, x: 50, y: 14, team: 'away' },
            { id: 'a9', number: 9, x: 50, y: 22, team: 'away' },
            { id: 'a10', number: 10, x: 60, y: 12, team: 'away' },
            { id: 'a12', number: 12, x: 40, y: 10, team: 'away' },
            { id: 'a13', number: 13, x: 70, y: 10, team: 'away' },
            { id: 'a11', number: 11, x: 18, y: 8, team: 'away' },
            { id: 'a14', number: 14, x: 88, y: 8, team: 'away' },
            { id: 'a15', number: 15, x: 50, y: 4, team: 'away' },
        ],
        ball: { x: 50, y: 28, visible: true },
        lines: [],
        viewBox: { x: 0, y: 0, w: SVG_W, h: 800 },
    },
    {
        id: 'free-kick',
        name: 'Free kick',
        category: 'Penales',
        players: [
            // Marca a la altura del centro (y=46). Quick tap del 9, pack listo para sostener el punto.
            { id: 'h1', number: 1, x: 38, y: 48, team: 'home' },
            { id: 'h2', number: 2, x: 46, y: 48, team: 'home' },
            { id: 'h3', number: 3, x: 54, y: 48, team: 'home' },
            { id: 'h4', number: 4, x: 40, y: 51, team: 'home' },
            { id: 'h5', number: 5, x: 52, y: 51, team: 'home' },
            { id: 'h6', number: 6, x: 32, y: 51, team: 'home' },
            { id: 'h7', number: 7, x: 60, y: 51, team: 'home' },
            { id: 'h8', number: 8, x: 46, y: 54, team: 'home' },
            { id: 'h9', number: 9, x: 50, y: 47, team: 'home' },
            { id: 'h10', number: 10, x: 60, y: 56, team: 'home' },
            { id: 'h12', number: 12, x: 50, y: 62, team: 'home' },
            { id: 'h13', number: 13, x: 68, y: 62, team: 'home' },
            { id: 'h11', number: 11, x: 18, y: 66, team: 'home' },
            { id: 'h14', number: 14, x: 88, y: 66, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 82, team: 'home' },
            // Rival a 10m de la marca (offside line en y=36), backs cubriendo el campo defensivo.
            { id: 'a1', number: 1, x: 38, y: 36, team: 'away' },
            { id: 'a2', number: 2, x: 46, y: 36, team: 'away' },
            { id: 'a3', number: 3, x: 54, y: 36, team: 'away' },
            { id: 'a4', number: 4, x: 30, y: 36, team: 'away' },
            { id: 'a5', number: 5, x: 62, y: 36, team: 'away' },
            { id: 'a6', number: 6, x: 22, y: 36, team: 'away' },
            { id: 'a7', number: 7, x: 70, y: 36, team: 'away' },
            { id: 'a8', number: 8, x: 50, y: 32, team: 'away' },
            { id: 'a9', number: 9, x: 50, y: 40, team: 'away' },
            { id: 'a10', number: 10, x: 60, y: 28, team: 'away' },
            { id: 'a12', number: 12, x: 38, y: 24, team: 'away' },
            { id: 'a13', number: 13, x: 56, y: 24, team: 'away' },
            { id: 'a11', number: 11, x: 16, y: 20, team: 'away' },
            { id: 'a14', number: 14, x: 88, y: 20, team: 'away' },
            { id: 'a15', number: 15, x: 50, y: 12, team: 'away' },
        ],
        ball: { x: 50, y: 46, visible: true },
        lines: [],
        viewBox: { x: 0, y: 0, w: SVG_W, h: SVG_H },
    },
    {
        id: 'defense-22',
        name: 'Defensa 22 propio',
        category: 'Defensa',
        players: [
            // Cortina defensiva sobre la linea de 22 (y=70). Forwards al centro, backs abriendo.
            { id: 'h11', number: 11, x: 6, y: 70, team: 'home' },
            { id: 'h6', number: 6, x: 16, y: 70, team: 'home' },
            { id: 'h1', number: 1, x: 24, y: 70, team: 'home' },
            { id: 'h4', number: 4, x: 32, y: 70, team: 'home' },
            { id: 'h2', number: 2, x: 40, y: 70, team: 'home' },
            { id: 'h5', number: 5, x: 48, y: 70, team: 'home' },
            { id: 'h3', number: 3, x: 56, y: 70, team: 'home' },
            { id: 'h7', number: 7, x: 64, y: 70, team: 'home' },
            { id: 'h8', number: 8, x: 72, y: 70, team: 'home' },
            { id: 'h12', number: 12, x: 80, y: 70, team: 'home' },
            { id: 'h13', number: 13, x: 88, y: 70, team: 'home' },
            { id: 'h14', number: 14, x: 95, y: 70, team: 'home' },
            // 9 sweeper detras del ruck, 10 organizando, 15 cubriendo el fondo.
            { id: 'h9', number: 9, x: 38, y: 76, team: 'home' },
            { id: 'h10', number: 10, x: 60, y: 78, team: 'home' },
            { id: 'h15', number: 15, x: 50, y: 86, team: 'home' },
            // Rival atacando justo enfrente de la cortina (a 2m, sobre la pelota).
            { id: 'a1', number: 1, x: 26, y: 66, team: 'away' },
            { id: 'a4', number: 4, x: 34, y: 66, team: 'away' },
            { id: 'a2', number: 2, x: 42, y: 66, team: 'away' },
            { id: 'a5', number: 5, x: 50, y: 66, team: 'away' },
            { id: 'a3', number: 3, x: 58, y: 66, team: 'away' },
            { id: 'a8', number: 8, x: 66, y: 66, team: 'away' },
            { id: 'a6', number: 6, x: 16, y: 66, team: 'away' },
            { id: 'a7', number: 7, x: 74, y: 66, team: 'away' },
            { id: 'a9', number: 9, x: 50, y: 60, team: 'away' },
            { id: 'a10', number: 10, x: 60, y: 54, team: 'away' },
            { id: 'a12', number: 12, x: 38, y: 50, team: 'away' },
            { id: 'a13', number: 13, x: 76, y: 50, team: 'away' },
            { id: 'a11', number: 11, x: 16, y: 46, team: 'away' },
            { id: 'a14', number: 14, x: 92, y: 46, team: 'away' },
            { id: 'a15', number: 15, x: 50, y: 38, team: 'away' },
        ],
        // Pelota en el ataque rival (zona de los 10m del rival rumbo al 22).
        ball: { x: 50, y: 64, visible: true },
        lines: [],
        viewBox: { x: 0, y: 200, w: SVG_W, h: 900 },
    },
];

export const DEFAULT_FORMATIONS: Record<string, PlayerChip[]> = {
    rugby: [
        { id: 'h1', number: 1, x: 35, y: 82, team: 'home' },
        { id: 'h2', number: 2, x: 50, y: 85, team: 'home' },
        { id: 'h3', number: 3, x: 65, y: 82, team: 'home' },
        { id: 'h4', number: 4, x: 45, y: 72, team: 'home' },
        { id: 'h5', number: 5, x: 55, y: 72, team: 'home' },
        { id: 'h6', number: 6, x: 35, y: 65, team: 'home' },
        { id: 'h7', number: 7, x: 65, y: 65, team: 'home' },
        { id: 'h8', number: 8, x: 50, y: 62, team: 'home' },
        { id: 'h9', number: 9, x: 50, y: 55, team: 'home' },
        { id: 'h10', number: 10, x: 50, y: 48, team: 'home' },
        { id: 'h11', number: 11, x: 25, y: 35, team: 'home' },
        { id: 'h12', number: 12, x: 40, y: 40, team: 'home' },
        { id: 'h13', number: 13, x: 60, y: 40, team: 'home' },
        { id: 'h14', number: 14, x: 75, y: 35, team: 'home' },
        { id: 'h15', number: 15, x: 50, y: 22, team: 'home' },
    ],
    football: [
        { id: 'h1', number: 1, x: 50, y: 90, team: 'home' },
        { id: 'h2', number: 2, x: 20, y: 78, team: 'home' },
        { id: 'h3', number: 4, x: 40, y: 80, team: 'home' },
        { id: 'h4', number: 5, x: 60, y: 80, team: 'home' },
        { id: 'h5', number: 3, x: 80, y: 78, team: 'home' },
        { id: 'h6', number: 8, x: 50, y: 62, team: 'home' },
        { id: 'h7', number: 6, x: 25, y: 55, team: 'home' },
        { id: 'h8', number: 7, x: 75, y: 55, team: 'home' },
        { id: 'h9', number: 10, x: 50, y: 45, team: 'home' },
        { id: 'h10', number: 11, x: 35, y: 35, team: 'home' },
        { id: 'h11', number: 9, x: 65, y: 35, team: 'home' },
    ],
    basketball: [
        { id: 'h1', number: 1, x: 20, y: 80, team: 'home' },
        { id: 'h2', number: 2, x: 50, y: 75, team: 'home' },
        { id: 'h3', number: 3, x: 80, y: 80, team: 'home' },
        { id: 'h4', number: 4, x: 35, y: 55, team: 'home' },
        { id: 'h5', number: 5, x: 65, y: 55, team: 'home' },
    ],
    hockey: [
        { id: 'h1', number: 1, x: 50, y: 88, team: 'home' },
        { id: 'h2', number: 2, x: 25, y: 75, team: 'home' },
        { id: 'h3', number: 3, x: 50, y: 70, team: 'home' },
        { id: 'h4', number: 4, x: 75, y: 75, team: 'home' },
        { id: 'h5', number: 5, x: 35, y: 58, team: 'home' },
        { id: 'h6', number: 6, x: 65, y: 58, team: 'home' },
        { id: 'h7', number: 7, x: 50, y: 50, team: 'home' },
        { id: 'h8', number: 8, x: 35, y: 38, team: 'home' },
        { id: 'h9', number: 9, x: 65, y: 38, team: 'home' },
        { id: 'h10', number: 10, x: 45, y: 25, team: 'home' },
        { id: 'h11', number: 11, x: 55, y: 25, team: 'home' },
    ],
};

export const DEFAULT_BALL = { x: 50, y: 55, visible: true };
export const DRAW_COLORS = ['#facc15', '#ef4444', '#3b82f6', '#22c55e', '#ffffff', '#f97316', '#a855f7'];
export const PLAYBACK_SPEEDS = [0.25, 0.5, 0.75, 1, 1.25, 1.5, 2];
export const FRAME_THUMB = {
    padX: 10,
    padY: 10,
    width: 72,
    height: 118,
    svgWidth: 92,
    svgHeight: 138,
};
