-- stg_urba_equipos_mayores — parte 1 de 1
--
-- Cada equipo que compite pasa a tener su propio registro en clubs, como ya
-- funcionan los juveniles. Sólo la categoría mayores (Superior) sigue apuntando
-- al registro de la institución.
--
-- Son 332 equipos que hoy comparten el registro de su institución. El caso que
-- lo hace visible: Newman F, Newman G y Newman H juegan el mismo torneo y los tres
-- escriben sobre club-newman, así que el motor los suma en una sola fila de la tabla.
--
-- OJO con el sufijo: es la letra del EQUIPO, no la del torneo. "Newman G" juega
-- "TOP 14 - Preintermedia F" y su triple es 9|preintermedia|G.
--
-- INSERT ... VALUES puro, ejecutable en el editor SQL. ON CONFLICT DO NOTHING.
-- NO trae el UPDATE de club_external_ids ni el INSERT en clubs: eso se arma aparte.

CREATE TABLE IF NOT EXISTS public.stg_urba_equipos_mayores (
    urba_club_id           INTEGER NOT NULL,
    categoria              TEXT    NOT NULL,
    sufijo                 TEXT    NOT NULL DEFAULT '''',
    external_id            TEXT    PRIMARY KEY,   -- el triple, tal como está en club_external_ids
    club_id_actual         TEXT    NOT NULL,      -- el registro de institución al que apunta HOY
    id_sugerido            TEXT    NOT NULL,
    nombre_sugerido        TEXT    NOT NULL,
    nombre_corto_sugerido  TEXT    NOT NULL
);

REVOKE ALL ON public.stg_urba_equipos_mayores FROM anon, authenticated;
ALTER TABLE public.stg_urba_equipos_mayores ENABLE ROW LEVEL SECURITY;

BEGIN;

INSERT INTO public.stg_urba_equipos_mayores (urba_club_id, categoria, sufijo, external_id, club_id_actual, id_sugerido, nombre_sugerido, nombre_corto_sugerido) VALUES
  (75, 'femenino', '', '75|femenino|', 'atletico-san-andres', 'atletico-san-andres-femenino', 'Atletico San Andres Femenino', 'Atletico San Andres Femenino'),
  (63, 'femenino', '', '63|femenino|', 'atletico-y-progreso', 'atletico-y-progreso-femenino', 'Atletico y Progreso Femenino', 'Atletico y Progreso Femenino'),
  (80, 'femenino', '', '80|femenino|', 'banco-hipotecario', 'banco-hipotecario-femenino', 'Banco Hipotecario Femenino', 'Banco Hipotecario Femenino'),
  (71, 'femenino', '', '71|femenino|', 'beromama', 'beromama-femenino', 'Beromama Femenino', 'Beromama Femenino'),
  (49, 'femenino', '', '49|femenino|', 'casa-de-padua', 'casa-de-padua-femenino', 'CASA de Padua Femenino', 'CASA de Padua Femenino'),
  (42, 'femenino', '', '42|femenino|', 'centro-naval', 'centro-naval-femenino', 'Centro Naval Femenino', 'Centro Naval Femenino'),
  (42, 'femenino', 'B', '42|femenino|B', 'centro-naval', 'centro-naval-femenino-b', 'Centro Naval Femenino "B"', 'Centro Naval Femenino "B"'),
  (76, 'femenino', '', '76|femenino|', 'ciudad-de-campana', 'ciudad-de-campana-femenino', 'Ciudad de Campana Femenino', 'Ciudad de Campana Femenino'),
  (54, 'femenino', '', '54|femenino|', 'ciudad-de-buenos-aires', 'ciudad-femenino', 'Ciudad Femenino', 'Ciudad Femenino'),
  (27, 'femenino', '', '27|femenino|', 'cuq', 'cuq-femenino', 'CUQ Femenino', 'CUQ Femenino'),
  (84, 'femenino', '', '84|femenino|', 'defensores-de-glew', 'defensores-de-glew-femenino', 'Defensores de Glew Femenino', 'Defensores de Glew Femenino'),
  (37, 'femenino', '', '37|femenino|', 'don-bosco', 'don-bosco-femenino', 'Don Bosco Femenino', 'Don Bosco Femenino'),
  (48, 'femenino', '', '48|femenino|', 'el-retiro', 'el-retiro-femenino', 'El Retiro Femenino', 'El Retiro Femenino'),
  (86, 'femenino', '', '86|femenino|', 'ezeiza', 'ezeiza-femenino', 'Ezeiza Femenino', 'Ezeiza Femenino'),
  (59, 'femenino', '', '59|femenino|', 'g-y-e-de-ituzaingo', 'g-y-e-de-ituzaingo-femenino', 'G y E de Ituzaingo Femenino', 'G y E de Ituzaingo Femenino'),
  (13, 'femenino', '', '13|femenino|', 'la-plata', 'la-plata-femenino', 'La Plata Femenino', 'La Plata Femenino'),
  (64, 'femenino', '', '64|femenino|', 'la-salle', 'la-salle-femenino', 'La Salle Femenino', 'La Salle Femenino'),
  (51, 'femenino', '', '51|femenino|', 'lanus-r-c', 'lanus-r-c-femenino', 'Lanús R.C. Femenino', 'Lanús R.C. Femenino'),
  (26, 'femenino', '', '26|femenino|', 'los-tilos', 'los-tilos-femenino', 'Los Tilos Femenino', 'Los Tilos Femenino'),
  (82, 'femenino', '', '82|femenino|', 'marcos-paz', 'marcos-paz-femenino', 'Marcos Paz Femenino', 'Marcos Paz Femenino'),
  (91, 'femenino', '', '91|femenino|', 'municipalidad-de-berazategui', 'municipalidad-de-berazategui-femenino', 'Municipalidad de Berazategui Femenino', 'Municipalidad de Berazategui Femenino'),
  (85, 'femenino', '', '85|femenino|', 'pac-general-rodriguez', 'pac-general-rodriguez-femenino', 'Pac General Rodriguez Femenino', 'Pac General Rodriguez Femenino'),
  (70, 'femenino', '', '70|femenino|', 'porteno', 'porteno-femenino', 'Porteño Femenino', 'Porteño Femenino'),
  (57, 'femenino', '', '57|femenino|', 'san-marcos', 'san-marcos-femenino', 'San Marcos Femenino', 'San Marcos Femenino'),
  (56, 'femenino', '', '56|femenino|', 'san-miguel-r-c', 'san-miguel-femenino', 'San Miguel Femenino', 'San Miguel Femenino'),
  (43, 'femenino', '', '43|femenino|', 'sitas', 'sitas-femenino', 'SITAS Femenino', 'SITAS Femenino'),
  (72, 'femenino', '', '72|femenino|', 'tigre', 'tigre-femenino', 'Tigre Femenino', 'Tigre Femenino'),
  (62, 'femenino', '', '62|femenino|', 'tiro-federal-de-san-pedro', 'tiro-federal-de-san-pedro-femenino', 'Tiro Federal de San Pedro Femenino', 'Tiro Federal de San Pedro Femenino'),
  (29, 'femenino', '', '29|femenino|', 'universitario-de-la-plata', 'univ-la-plata-femenino', 'Univ. La Plata Femenino', 'Univ. La Plata Femenino'),
  (106, 'femenino', '', '106|femenino|', 'univ-nac-de-la-matanza', 'univ-nac-de-la-matanza-femenino', 'Univ. Nac de la Matanza Femenino', 'Univ. Nac de la Matanza Femenino'),
  (95, 'femenino', '', '95|femenino|', 'univ-nac-de-la-plata', 'univ-nac-de-la-plata-femenino', 'Univ. Nac de la Plata Femenino', 'Univ. Nac de la Plata Femenino'),
  (77, 'femenino', '', '77|femenino|', 'vicente-lopez', 'vicente-lopez-femenino', 'Vicente Lopez Femenino', 'Vicente Lopez Femenino'),
  (61, 'intermedia', '', '61|intermedia|', 'albatros', 'albatros-intermedia', 'Albatros Intermedia', 'Albatros Intermedia'),
  (74, 'intermedia', '', '74|intermedia|', 'almafuerte', 'almafuerte-intermedia', 'Almafuerte Intermedia', 'Almafuerte Intermedia'),
  (12, 'intermedia', '', '12|intermedia|', 'asoc-alumni', 'alumni-intermedia', 'Alumni Intermedia', 'Alumni Intermedia'),
  (53, 'intermedia', '', '53|intermedia|', 'argentino-r-c', 'argentino-r-c-intermedia', 'Argentino R.C. Intermedia', 'Argentino R.C. Intermedia'),
  (67, 'intermedia', '', '67|intermedia|', 'arsenal-zarate', 'arsenal-zarate-intermedia', 'Arsenal Zarate Intermedia', 'Arsenal Zarate Intermedia'),
  (10, 'intermedia', '', '10|intermedia|', 'atletico-del-rosario', 'atl-del-rosario-intermedia', 'Atl. del Rosario Intermedia', 'Atl. del Rosario Intermedia'),
  (60, 'intermedia', '', '60|intermedia|', 'atletico-chascomus', 'atletico-chascomus-intermedia', 'Atletico Chascomus Intermedia', 'Atletico Chascomus Intermedia'),
  (75, 'intermedia', '', '75|intermedia|', 'atletico-san-andres', 'atletico-san-andres-intermedia', 'Atletico San Andres Intermedia', 'Atletico San Andres Intermedia'),
  (63, 'intermedia', '', '63|intermedia|', 'atletico-y-progreso', 'atletico-y-progreso-intermedia', 'Atletico y Progreso Intermedia', 'Atletico y Progreso Intermedia'),
  (80, 'intermedia', '', '80|intermedia|', 'banco-hipotecario', 'banco-hipotecario-intermedia', 'Banco Hipotecario Intermedia', 'Banco Hipotecario Intermedia'),
  (40, 'intermedia', '', '40|intermedia|', 'banco-nacion', 'banco-nacion-intermedia', 'Banco Nación Intermedia', 'Banco Nación Intermedia'),
  (7, 'intermedia', '', '7|intermedia|', 'belgrano-athletic', 'belgrano-ath-intermedia', 'Belgrano Ath. Intermedia', 'Belgrano Ath. Intermedia'),
  (89, 'intermedia', '', '89|intermedia|', 'berisso', 'berisso-intermedia', 'Berisso Intermedia', 'Berisso Intermedia'),
  (71, 'intermedia', '', '71|intermedia|', 'beromama', 'beromama-intermedia', 'Beromama Intermedia', 'Beromama Intermedia'),
  (8, 'intermedia', '', '8|intermedia|', 'buenos-aires-crc', 'biei-intermedia', 'BIEI Intermedia', 'BIEI Intermedia'),
  (49, 'intermedia', '', '49|intermedia|', 'casa-de-padua', 'casa-de-padua-intermedia', 'CASA de Padua Intermedia', 'CASA de Padua Intermedia'),
  (3, 'intermedia', '', '3|intermedia|', 'casi', 'casi-intermedia', 'CASI Intermedia', 'CASI Intermedia'),
  (42, 'intermedia', '', '42|intermedia|', 'centro-naval', 'centro-naval-intermedia', 'Centro Naval Intermedia', 'Centro Naval Intermedia'),
  (11, 'intermedia', '', '11|intermedia|', 'club-champagnat', 'champagnat-intermedia', 'Champagnat Intermedia', 'Champagnat Intermedia'),
  (76, 'intermedia', '', '76|intermedia|', 'ciudad-de-campana', 'ciudad-de-campana-intermedia', 'Ciudad de Campana Intermedia', 'Ciudad de Campana Intermedia'),
  (54, 'intermedia', '', '54|intermedia|', 'ciudad-de-buenos-aires', 'ciudad-intermedia', 'Ciudad Intermedia', 'Ciudad Intermedia'),
  (46, 'intermedia', '', '46|intermedia|', 'club-areco', 'club-areco-intermedia', 'Club Areco Intermedia', 'Club Areco Intermedia'),
  (28, 'intermedia', '', '28|intermedia|', 'club-italiano', 'club-italiano-intermedia', 'Club Italiano Intermedia', 'Club Italiano Intermedia'),
  (16, 'intermedia', '', '16|intermedia|', 'club-pucara', 'club-pucara-intermedia', 'Club Pucará Intermedia', 'Club Pucará Intermedia'),
  (2, 'intermedia', '', '2|intermedia|', 'cuba', 'cuba-intermedia', 'CUBA Intermedia', 'CUBA Intermedia'),
  (27, 'intermedia', '', '27|intermedia|', 'cuq', 'cuq-intermedia', 'CUQ Intermedia', 'CUQ Intermedia'),
  (24, 'intermedia', '', '24|intermedia|', 'curupayti', 'curupayti-intermedia', 'Curupaytí Intermedia', 'Curupaytí Intermedia'),
  (52, 'intermedia', '', '52|intermedia|', 'club-daom', 'daom-intermedia', 'Daom Intermedia', 'Daom Intermedia'),
  (84, 'intermedia', '', '84|intermedia|', 'defensores-de-glew', 'defensores-de-glew-intermedia', 'Defensores de Glew Intermedia', 'Defensores de Glew Intermedia'),
  (44, 'intermedia', '', '44|intermedia|', 'asoc-del-sur', 'del-sur-intermedia', 'Del Sur Intermedia', 'Del Sur Intermedia'),
  (33, 'intermedia', '', '33|intermedia|', 'delta-r-c', 'delta-r-c-intermedia', 'Delta R.C. Intermedia', 'Delta R.C. Intermedia'),
  (17, 'intermedia', '', '17|intermedia|', 'deportiva-francesa', 'dep-francesa-intermedia', 'Dep. Francesa Intermedia', 'Dep. Francesa Intermedia'),
  (37, 'intermedia', '', '37|intermedia|', 'don-bosco', 'don-bosco-intermedia', 'Don Bosco Intermedia', 'Don Bosco Intermedia'),
  (48, 'intermedia', '', '48|intermedia|', 'el-retiro', 'el-retiro-intermedia', 'El Retiro Intermedia', 'El Retiro Intermedia'),
  (86, 'intermedia', '', '86|intermedia|', 'ezeiza', 'ezeiza-intermedia', 'Ezeiza Intermedia', 'Ezeiza Intermedia'),
  (87, 'intermedia', '', '87|intermedia|', 'floresta', 'floresta-intermedia', 'Floresta Intermedia', 'Floresta Intermedia'),
  (59, 'intermedia', '', '59|intermedia|', 'g-y-e-de-ituzaingo', 'g-y-e-de-ituzaingo-intermedia', 'G y E de Ituzaingo Intermedia', 'G y E de Ituzaingo Intermedia'),
  (30, 'intermedia', '', '30|intermedia|', 'geba', 'geba-intermedia', 'GEBA Intermedia', 'GEBA Intermedia'),
  (6, 'intermedia', '', '6|intermedia|', 'hindu-club', 'hindu-intermedia', 'Hindú Intermedia', 'Hindú Intermedia'),
  (19, 'intermedia', '', '19|intermedia|', 'hurling', 'hurling-intermedia', 'Hurling Intermedia', 'Hurling Intermedia'),
  (13, 'intermedia', '', '13|intermedia|', 'la-plata', 'la-plata-intermedia', 'La Plata Intermedia', 'La Plata Intermedia'),
  (64, 'intermedia', '', '64|intermedia|', 'la-salle', 'la-salle-intermedia', 'La Salle Intermedia', 'La Salle Intermedia'),
  (51, 'intermedia', '', '51|intermedia|', 'lanus-r-c', 'lanus-r-c-intermedia', 'Lanús R.C. Intermedia', 'Lanús R.C. Intermedia'),
  (73, 'intermedia', '', '73|intermedia|', 'las-canas', 'las-canas-intermedia', 'Las Cañas Intermedia', 'Las Cañas Intermedia'),
  (36, 'intermedia', '', '36|intermedia|', 'liceo-militar', 'liceo-militar-intermedia', 'Liceo Militar Intermedia', 'Liceo Militar Intermedia'),
  (38, 'intermedia', '', '38|intermedia|', 'liceo-naval', 'liceo-naval-intermedia', 'Liceo Naval Intermedia', 'Liceo Naval Intermedia'),
  (15, 'intermedia', '', '15|intermedia|', 'lomas-athletic', 'lomas-ath-intermedia', 'Lomas Ath. Intermedia', 'Lomas Ath. Intermedia'),
  (78, 'intermedia', '', '78|intermedia|', 'los-cedros', 'los-cedros-intermedia', 'Los Cedros Intermedia', 'Los Cedros Intermedia'),
  (23, 'intermedia', '', '23|intermedia|', 'los-matreros', 'los-matreros-intermedia', 'Los Matreros Intermedia', 'Los Matreros Intermedia'),
  (65, 'intermedia', '', '65|intermedia|', 'los-molinos', 'los-molinos-intermedia', 'Los Molinos Intermedia', 'Los Molinos Intermedia'),
  (79, 'intermedia', '', '79|intermedia|', 'los-pinos', 'los-pinos-intermedia', 'Los Pinos Intermedia', 'Los Pinos Intermedia'),
  (26, 'intermedia', '', '26|intermedia|', 'los-tilos', 'los-tilos-intermedia', 'Los Tilos Intermedia', 'Los Tilos Intermedia'),
  (50, 'intermedia', '', '50|intermedia|', 'lujan-r-c', 'lujan-r-c-intermedia', 'Lujan R.C. Intermedia', 'Lujan R.C. Intermedia'),
  (34, 'intermedia', '', '34|intermedia|', 'manuel-belgrano', 'manuel-belgrano-intermedia', 'Manuel Belgrano Intermedia', 'Manuel Belgrano Intermedia'),
  (82, 'intermedia', '', '82|intermedia|', 'marcos-paz', 'marcos-paz-intermedia', 'Marcos Paz Intermedia', 'Marcos Paz Intermedia'),
  (39, 'intermedia', '', '39|intermedia|', 'mariano-moreno', 'mariano-moreno-intermedia', 'Mariano Moreno Intermedia', 'Mariano Moreno Intermedia'),
  (47, 'intermedia', '', '47|intermedia|', 'mercedes', 'mercedes-intermedia', 'Mercedes Intermedia', 'Mercedes Intermedia'),
  (41, 'intermedia', '', '41|intermedia|', 'monte-grande', 'monte-grande-intermedia', 'Monte Grande Intermedia', 'Monte Grande Intermedia'),
  (91, 'intermedia', '', '91|intermedia|', 'municipalidad-de-berazategui', 'municipalidad-de-berazategui-intermedia', 'Municipalidad de Berazategui Intermedia', 'Municipalidad de Berazategui Intermedia'),
  (9, 'intermedia', '', '9|intermedia|', 'club-newman', 'newman-intermedia', 'Newman Intermedia', 'Newman Intermedia'),
  (90, 'intermedia', '', '90|intermedia|', 'obras-sanitarias', 'obras-sanitarias-intermedia', 'Obras Sanitarias Intermedia', 'Obras Sanitarias Intermedia'),
  (66, 'intermedia', '', '66|intermedia|', 'old-georgian', 'old-georgian-intermedia', 'Old Georgian Intermedia', 'Old Georgian Intermedia'),
  (22, 'intermedia', '', '22|intermedia|', 'olivos-r-c', 'olivos-r-c-intermedia', 'Olivos R.C. Intermedia', 'Olivos R.C. Intermedia'),
  (85, 'intermedia', '', '85|intermedia|', 'pac-general-rodriguez', 'pac-general-rodriguez-intermedia', 'Pac General Rodriguez Intermedia', 'Pac General Rodriguez Intermedia'),
  (70, 'intermedia', '', '70|intermedia|', 'porteno', 'porteno-intermedia', 'Porteño Intermedia', 'Porteño Intermedia'),
  (25, 'intermedia', '', '25|intermedia|', 'pueyrredon', 'pueyrredon-intermedia', 'Pueyrredón Intermedia', 'Pueyrredón Intermedia'),
  (4, 'intermedia', '', '4|intermedia|', 'regatas-de-bella-vista', 'regatas-bv-intermedia', 'Regatas BV Intermedia', 'Regatas BV Intermedia'),
  (88, 'intermedia', '', '88|intermedia|', 'rivadavia-de-lobos', 'rivadavia-de-lobos-intermedia', 'Rivadavia de Lobos Intermedia', 'Rivadavia de Lobos Intermedia'),
  (14, 'intermedia', '', '14|intermedia|', 'san-albano', 'san-albano-intermedia', 'San Albano Intermedia', 'San Albano Intermedia'),
  (31, 'intermedia', '', '31|intermedia|', 'san-andres', 'san-andres-intermedia', 'San Andrés Intermedia', 'San Andrés Intermedia'),
  (35, 'intermedia', '', '35|intermedia|', 'san-carlos', 'san-carlos-intermedia', 'San Carlos Intermedia', 'San Carlos Intermedia'),
  (18, 'intermedia', '', '18|intermedia|', 'san-cirano', 'san-cirano-intermedia', 'San Cirano Intermedia', 'San Cirano Intermedia'),
  (32, 'intermedia', '', '32|intermedia|', 'san-fernando', 'san-fernando-intermedia', 'San Fernando Intermedia', 'San Fernando Intermedia'),
  (83, 'intermedia', '', '83|intermedia|', 'san-jose', 'san-jose-intermedia', 'San José Intermedia', 'San José Intermedia'),
  (5, 'intermedia', '', '5|intermedia|', 'san-luis', 'san-luis-intermedia', 'San Luis Intermedia', 'San Luis Intermedia'),
  (57, 'intermedia', '', '57|intermedia|', 'san-marcos', 'san-marcos-intermedia', 'San Marcos Intermedia', 'San Marcos Intermedia'),
  (20, 'intermedia', '', '20|intermedia|', 'san-martin', 'san-martin-intermedia', 'San Martín Intermedia', 'San Martín Intermedia'),
  (56, 'intermedia', '', '56|intermedia|', 'san-miguel-r-c', 'san-miguel-intermedia', 'San Miguel Intermedia', 'San Miguel Intermedia'),
  (21, 'intermedia', '', '21|intermedia|', 'club-san-patricio', 'san-patricio-intermedia', 'San Patricio Intermedia', 'San Patricio Intermedia'),
  (1, 'intermedia', '', '1|intermedia|', 'san-isidro-club', 'sic-intermedia', 'SIC Intermedia', 'SIC Intermedia'),
  (43, 'intermedia', '', '43|intermedia|', 'sitas', 'sitas-intermedia', 'SITAS Intermedia', 'SITAS Intermedia'),
  (81, 'intermedia', '', '81|intermedia|', 'sociedad-hebraica', 'sociedad-hebraica-intermedia', 'Sociedad Hebraica Intermedia', 'Sociedad Hebraica Intermedia'),
  (58, 'intermedia', '', '58|intermedia|', 'st-brendan-s', 'st-brendans-intermedia', 'St. Brendan''s Intermedia', 'St. Brendan''s Intermedia'),
  (72, 'intermedia', '', '72|intermedia|', 'tigre', 'tigre-intermedia', 'Tigre Intermedia', 'Tigre Intermedia'),
  (69, 'intermedia', '', '69|intermedia|', 'tiro-federal-de-baradero', 'tiro-federal-de-baradero-intermedia', 'Tiro Federal de Baradero Intermedia', 'Tiro Federal de Baradero Intermedia'),
  (62, 'intermedia', '', '62|intermedia|', 'tiro-federal-de-san-pedro', 'tiro-federal-de-san-pedro-intermedia', 'Tiro Federal de San Pedro Intermedia', 'Tiro Federal de San Pedro Intermedia'),
  (29, 'intermedia', '', '29|intermedia|', 'universitario-de-la-plata', 'univ-la-plata-intermedia', 'Univ. La Plata Intermedia', 'Univ. La Plata Intermedia'),
  (68, 'intermedia', '', '68|intermedia|', 'varela-jr', 'varela-jr-intermedia', 'Varela Jr. Intermedia', 'Varela Jr. Intermedia'),
  (77, 'intermedia', '', '77|intermedia|', 'vicente-lopez', 'vicente-lopez-intermedia', 'Vicente Lopez Intermedia', 'Vicente Lopez Intermedia'),
  (45, 'intermedia', '', '45|intermedia|', 'vicentinos', 'vicentinos-intermedia', 'Vicentinos Intermedia', 'Vicentinos Intermedia'),
  (55, 'intermedia', '', '55|intermedia|', 'virreyes-r-c', 'virreyes-r-c-intermedia', 'Virreyes R.C. Intermedia', 'Virreyes R.C. Intermedia'),
  (12, 'preintermedia', '', '12|preintermedia|', 'asoc-alumni', 'alumni-preintermedia', 'Alumni Preintermedia', 'Alumni Preintermedia'),
  (12, 'preintermedia', 'B', '12|preintermedia|B', 'asoc-alumni', 'alumni-preintermedia-b', 'Alumni Preintermedia "B"', 'Alumni Preintermedia "B"'),
  (12, 'preintermedia', 'C', '12|preintermedia|C', 'asoc-alumni', 'alumni-preintermedia-c', 'Alumni Preintermedia "C"', 'Alumni Preintermedia "C"'),
  (12, 'preintermedia', 'D', '12|preintermedia|D', 'asoc-alumni', 'alumni-preintermedia-d', 'Alumni Preintermedia "D"', 'Alumni Preintermedia "D"'),
  (12, 'preintermedia', 'E', '12|preintermedia|E', 'asoc-alumni', 'alumni-preintermedia-e', 'Alumni Preintermedia "E"', 'Alumni Preintermedia "E"'),
  (12, 'preintermedia', 'F', '12|preintermedia|F', 'asoc-alumni', 'alumni-preintermedia-f', 'Alumni Preintermedia "F"', 'Alumni Preintermedia "F"'),
  (53, 'preintermedia', '', '53|preintermedia|', 'argentino-r-c', 'argentino-r-c-preintermedia', 'Argentino R.C. Preintermedia', 'Argentino R.C. Preintermedia'),
  (53, 'preintermedia', 'A', '53|preintermedia|A', 'argentino-r-c', 'argentino-r-c-preintermedia-a', 'Argentino R.C. Preintermedia "A"', 'Argentino R.C. Preintermedia "A"'),
  (53, 'preintermedia', 'B', '53|preintermedia|B', 'argentino-r-c', 'argentino-r-c-preintermedia-b', 'Argentino R.C. Preintermedia "B"', 'Argentino R.C. Preintermedia "B"'),
  (53, 'preintermedia', 'C', '53|preintermedia|C', 'argentino-r-c', 'argentino-r-c-preintermedia-c', 'Argentino R.C. Preintermedia "C"', 'Argentino R.C. Preintermedia "C"'),
  (10, 'preintermedia', '', '10|preintermedia|', 'atletico-del-rosario', 'atl-del-rosario-preintermedia', 'Atl. del Rosario Preintermedia', 'Atl. del Rosario Preintermedia'),
  (10, 'preintermedia', 'B', '10|preintermedia|B', 'atletico-del-rosario', 'atl-del-rosario-preintermedia-b', 'Atl. del Rosario Preintermedia "B"', 'Atl. del Rosario Preintermedia "B"'),
  (10, 'preintermedia', 'C', '10|preintermedia|C', 'atletico-del-rosario', 'atl-del-rosario-preintermedia-c', 'Atl. del Rosario Preintermedia "C"', 'Atl. del Rosario Preintermedia "C"'),
  (10, 'preintermedia', 'D', '10|preintermedia|D', 'atletico-del-rosario', 'atl-del-rosario-preintermedia-d', 'Atl. del Rosario Preintermedia "D"', 'Atl. del Rosario Preintermedia "D"'),
  (63, 'preintermedia', '', '63|preintermedia|', 'atletico-y-progreso', 'atletico-y-progreso-preintermedia', 'Atletico y Progreso Preintermedia', 'Atletico y Progreso Preintermedia'),
  (40, 'preintermedia', '', '40|preintermedia|', 'banco-nacion', 'banco-nacion-preintermedia', 'Banco Nación Preintermedia', 'Banco Nación Preintermedia'),
  (40, 'preintermedia', 'B', '40|preintermedia|B', 'banco-nacion', 'banco-nacion-preintermedia-b', 'Banco Nación Preintermedia "B"', 'Banco Nación Preintermedia "B"'),
  (7, 'preintermedia', '', '7|preintermedia|', 'belgrano-athletic', 'belgrano-ath-preintermedia', 'Belgrano Ath. Preintermedia', 'Belgrano Ath. Preintermedia'),
  (7, 'preintermedia', 'B', '7|preintermedia|B', 'belgrano-athletic', 'belgrano-ath-preintermedia-b', 'Belgrano Ath. Preintermedia "B"', 'Belgrano Ath. Preintermedia "B"'),
  (7, 'preintermedia', 'C', '7|preintermedia|C', 'belgrano-athletic', 'belgrano-ath-preintermedia-c', 'Belgrano Ath. Preintermedia "C"', 'Belgrano Ath. Preintermedia "C"'),
  (7, 'preintermedia', 'D', '7|preintermedia|D', 'belgrano-athletic', 'belgrano-ath-preintermedia-d', 'Belgrano Ath. Preintermedia "D"', 'Belgrano Ath. Preintermedia "D"'),
  (7, 'preintermedia', 'E', '7|preintermedia|E', 'belgrano-athletic', 'belgrano-ath-preintermedia-e', 'Belgrano Ath. Preintermedia "E"', 'Belgrano Ath. Preintermedia "E"'),
  (7, 'preintermedia', 'F', '7|preintermedia|F', 'belgrano-athletic', 'belgrano-ath-preintermedia-f', 'Belgrano Ath. Preintermedia "F"', 'Belgrano Ath. Preintermedia "F"'),
  (8, 'preintermedia', '', '8|preintermedia|', 'buenos-aires-crc', 'biei-preintermedia', 'BIEI Preintermedia', 'BIEI Preintermedia'),
  (8, 'preintermedia', 'B', '8|preintermedia|B', 'buenos-aires-crc', 'biei-preintermedia-b', 'BIEI Preintermedia "B"', 'BIEI Preintermedia "B"'),
  (8, 'preintermedia', 'C', '8|preintermedia|C', 'buenos-aires-crc', 'biei-preintermedia-c', 'BIEI Preintermedia "C"', 'BIEI Preintermedia "C"'),
  (8, 'preintermedia', 'D', '8|preintermedia|D', 'buenos-aires-crc', 'biei-preintermedia-d', 'BIEI Preintermedia "D"', 'BIEI Preintermedia "D"'),
  (8, 'preintermedia', 'E', '8|preintermedia|E', 'buenos-aires-crc', 'biei-preintermedia-e', 'BIEI Preintermedia "E"', 'BIEI Preintermedia "E"'),
  (49, 'preintermedia', '', '49|preintermedia|', 'casa-de-padua', 'casa-de-padua-preintermedia', 'CASA de Padua Preintermedia', 'CASA de Padua Preintermedia'),
  (49, 'preintermedia', 'B', '49|preintermedia|B', 'casa-de-padua', 'casa-de-padua-preintermedia-b', 'CASA de Padua Preintermedia "B"', 'CASA de Padua Preintermedia "B"'),
  (3, 'preintermedia', '', '3|preintermedia|', 'casi', 'casi-preintermedia', 'CASI Preintermedia', 'CASI Preintermedia'),
  (3, 'preintermedia', 'B', '3|preintermedia|B', 'casi', 'casi-preintermedia-b', 'CASI Preintermedia "B"', 'CASI Preintermedia "B"'),
  (3, 'preintermedia', 'C', '3|preintermedia|C', 'casi', 'casi-preintermedia-c', 'CASI Preintermedia "C"', 'CASI Preintermedia "C"'),
  (3, 'preintermedia', 'D', '3|preintermedia|D', 'casi', 'casi-preintermedia-d', 'CASI Preintermedia "D"', 'CASI Preintermedia "D"'),
  (3, 'preintermedia', 'E', '3|preintermedia|E', 'casi', 'casi-preintermedia-e', 'CASI Preintermedia "E"', 'CASI Preintermedia "E"'),
  (3, 'preintermedia', 'F', '3|preintermedia|F', 'casi', 'casi-preintermedia-f', 'CASI Preintermedia "F"', 'CASI Preintermedia "F"'),
  (42, 'preintermedia', '', '42|preintermedia|', 'centro-naval', 'centro-naval-preintermedia', 'Centro Naval Preintermedia', 'Centro Naval Preintermedia'),
  (42, 'preintermedia', 'B', '42|preintermedia|B', 'centro-naval', 'centro-naval-preintermedia-b', 'Centro Naval Preintermedia "B"', 'Centro Naval Preintermedia "B"'),
  (11, 'preintermedia', '', '11|preintermedia|', 'club-champagnat', 'champagnat-preintermedia', 'Champagnat Preintermedia', 'Champagnat Preintermedia'),
  (11, 'preintermedia', 'B', '11|preintermedia|B', 'club-champagnat', 'champagnat-preintermedia-b', 'Champagnat Preintermedia "B"', 'Champagnat Preintermedia "B"'),
  (11, 'preintermedia', 'C', '11|preintermedia|C', 'club-champagnat', 'champagnat-preintermedia-c', 'Champagnat Preintermedia "C"', 'Champagnat Preintermedia "C"'),
  (11, 'preintermedia', 'D', '11|preintermedia|D', 'club-champagnat', 'champagnat-preintermedia-d', 'Champagnat Preintermedia "D"', 'Champagnat Preintermedia "D"'),
  (11, 'preintermedia', 'E', '11|preintermedia|E', 'club-champagnat', 'champagnat-preintermedia-e', 'Champagnat Preintermedia "E"', 'Champagnat Preintermedia "E"'),
  (11, 'preintermedia', 'F', '11|preintermedia|F', 'club-champagnat', 'champagnat-preintermedia-f', 'Champagnat Preintermedia "F"', 'Champagnat Preintermedia "F"'),
  (54, 'preintermedia', '', '54|preintermedia|', 'ciudad-de-buenos-aires', 'ciudad-preintermedia', 'Ciudad Preintermedia', 'Ciudad Preintermedia'),
  (54, 'preintermedia', 'B', '54|preintermedia|B', 'ciudad-de-buenos-aires', 'ciudad-preintermedia-b', 'Ciudad Preintermedia "B"', 'Ciudad Preintermedia "B"'),
  (46, 'preintermedia', '', '46|preintermedia|', 'club-areco', 'club-areco-preintermedia', 'Club Areco Preintermedia', 'Club Areco Preintermedia'),
  (28, 'preintermedia', '', '28|preintermedia|', 'club-italiano', 'club-italiano-preintermedia', 'Club Italiano Preintermedia', 'Club Italiano Preintermedia'),
  (28, 'preintermedia', 'B', '28|preintermedia|B', 'club-italiano', 'club-italiano-preintermedia-b', 'Club Italiano Preintermedia "B"', 'Club Italiano Preintermedia "B"'),
  (16, 'preintermedia', '', '16|preintermedia|', 'club-pucara', 'club-pucara-preintermedia', 'Club Pucará Preintermedia', 'Club Pucará Preintermedia'),
  (16, 'preintermedia', 'B', '16|preintermedia|B', 'club-pucara', 'club-pucara-preintermedia-b', 'Club Pucará Preintermedia "B"', 'Club Pucará Preintermedia "B"'),
  (16, 'preintermedia', 'C', '16|preintermedia|C', 'club-pucara', 'club-pucara-preintermedia-c', 'Club Pucará Preintermedia "C"', 'Club Pucará Preintermedia "C"'),
  (16, 'preintermedia', 'D', '16|preintermedia|D', 'club-pucara', 'club-pucara-preintermedia-d', 'Club Pucará Preintermedia "D"', 'Club Pucará Preintermedia "D"'),
  (16, 'preintermedia', 'E', '16|preintermedia|E', 'club-pucara', 'club-pucara-preintermedia-e', 'Club Pucará Preintermedia "E"', 'Club Pucará Preintermedia "E"'),
  (2, 'preintermedia', '', '2|preintermedia|', 'cuba', 'cuba-preintermedia', 'CUBA Preintermedia', 'CUBA Preintermedia'),
  (2, 'preintermedia', 'B', '2|preintermedia|B', 'cuba', 'cuba-preintermedia-b', 'CUBA Preintermedia "B"', 'CUBA Preintermedia "B"'),
  (2, 'preintermedia', 'C', '2|preintermedia|C', 'cuba', 'cuba-preintermedia-c', 'CUBA Preintermedia "C"', 'CUBA Preintermedia "C"'),
  (2, 'preintermedia', 'D', '2|preintermedia|D', 'cuba', 'cuba-preintermedia-d', 'CUBA Preintermedia "D"', 'CUBA Preintermedia "D"'),
  (2, 'preintermedia', 'E', '2|preintermedia|E', 'cuba', 'cuba-preintermedia-e', 'CUBA Preintermedia "E"', 'CUBA Preintermedia "E"'),
  (2, 'preintermedia', 'F', '2|preintermedia|F', 'cuba', 'cuba-preintermedia-f', 'CUBA Preintermedia "F"', 'CUBA Preintermedia "F"'),
  (2, 'preintermedia', 'G', '2|preintermedia|G', 'cuba', 'cuba-preintermedia-g', 'CUBA Preintermedia "G"', 'CUBA Preintermedia "G"'),
  (27, 'preintermedia', '', '27|preintermedia|', 'cuq', 'cuq-preintermedia', 'CUQ Preintermedia', 'CUQ Preintermedia'),
  (27, 'preintermedia', 'B', '27|preintermedia|B', 'cuq', 'cuq-preintermedia-b', 'CUQ Preintermedia "B"', 'CUQ Preintermedia "B"'),
  (27, 'preintermedia', 'C', '27|preintermedia|C', 'cuq', 'cuq-preintermedia-c', 'CUQ Preintermedia "C"', 'CUQ Preintermedia "C"'),
  (24, 'preintermedia', '', '24|preintermedia|', 'curupayti', 'curupayti-preintermedia', 'Curupaytí Preintermedia', 'Curupaytí Preintermedia'),
  (24, 'preintermedia', 'B', '24|preintermedia|B', 'curupayti', 'curupayti-preintermedia-b', 'Curupaytí Preintermedia "B"', 'Curupaytí Preintermedia "B"'),
  (24, 'preintermedia', 'C', '24|preintermedia|C', 'curupayti', 'curupayti-preintermedia-c', 'Curupaytí Preintermedia "C"', 'Curupaytí Preintermedia "C"'),
  (24, 'preintermedia', 'D', '24|preintermedia|D', 'curupayti', 'curupayti-preintermedia-d', 'Curupaytí Preintermedia "D"', 'Curupaytí Preintermedia "D"'),
  (24, 'preintermedia', 'E', '24|preintermedia|E', 'curupayti', 'curupayti-preintermedia-e', 'Curupaytí Preintermedia "E"', 'Curupaytí Preintermedia "E"'),
  (52, 'preintermedia', '', '52|preintermedia|', 'club-daom', 'daom-preintermedia', 'Daom Preintermedia', 'Daom Preintermedia'),
  (44, 'preintermedia', '', '44|preintermedia|', 'asoc-del-sur', 'del-sur-preintermedia', 'Del Sur Preintermedia', 'Del Sur Preintermedia'),
  (33, 'preintermedia', '', '33|preintermedia|', 'delta-r-c', 'delta-r-c-preintermedia', 'Delta R.C. Preintermedia', 'Delta R.C. Preintermedia'),
  (33, 'preintermedia', 'B', '33|preintermedia|B', 'delta-r-c', 'delta-r-c-preintermedia-b', 'Delta R.C. Preintermedia "B"', 'Delta R.C. Preintermedia "B"'),
  (33, 'preintermedia', 'C', '33|preintermedia|C', 'delta-r-c', 'delta-r-c-preintermedia-c', 'Delta R.C. Preintermedia "C"', 'Delta R.C. Preintermedia "C"'),
  (17, 'preintermedia', '', '17|preintermedia|', 'deportiva-francesa', 'dep-francesa-preintermedia', 'Dep. Francesa Preintermedia', 'Dep. Francesa Preintermedia'),
  (17, 'preintermedia', 'B', '17|preintermedia|B', 'deportiva-francesa', 'dep-francesa-preintermedia-b', 'Dep. Francesa Preintermedia "B"', 'Dep. Francesa Preintermedia "B"'),
  (17, 'preintermedia', 'C', '17|preintermedia|C', 'deportiva-francesa', 'dep-francesa-preintermedia-c', 'Dep. Francesa Preintermedia "C"', 'Dep. Francesa Preintermedia "C"'),
  (17, 'preintermedia', 'D', '17|preintermedia|D', 'deportiva-francesa', 'dep-francesa-preintermedia-d', 'Dep. Francesa Preintermedia "D"', 'Dep. Francesa Preintermedia "D"'),
  (17, 'preintermedia', 'E', '17|preintermedia|E', 'deportiva-francesa', 'dep-francesa-preintermedia-e', 'Dep. Francesa Preintermedia "E"', 'Dep. Francesa Preintermedia "E"'),
  (37, 'preintermedia', '', '37|preintermedia|', 'don-bosco', 'don-bosco-preintermedia', 'Don Bosco Preintermedia', 'Don Bosco Preintermedia'),
  (37, 'preintermedia', 'B', '37|preintermedia|B', 'don-bosco', 'don-bosco-preintermedia-b', 'Don Bosco Preintermedia "B"', 'Don Bosco Preintermedia "B"'),
  (37, 'preintermedia', 'C', '37|preintermedia|C', 'don-bosco', 'don-bosco-preintermedia-c', 'Don Bosco Preintermedia "C"', 'Don Bosco Preintermedia "C"'),
  (48, 'preintermedia', '', '48|preintermedia|', 'el-retiro', 'el-retiro-preintermedia', 'El Retiro Preintermedia', 'El Retiro Preintermedia'),
  (59, 'preintermedia', '', '59|preintermedia|', 'g-y-e-de-ituzaingo', 'g-y-e-de-ituzaingo-preintermedia', 'G y E de Ituzaingo Preintermedia', 'G y E de Ituzaingo Preintermedia'),
  (30, 'preintermedia', '', '30|preintermedia|', 'geba', 'geba-preintermedia', 'GEBA Preintermedia', 'GEBA Preintermedia'),
  (30, 'preintermedia', 'B', '30|preintermedia|B', 'geba', 'geba-preintermedia-b', 'GEBA Preintermedia "B"', 'GEBA Preintermedia "B"'),
  (30, 'preintermedia', 'C', '30|preintermedia|C', 'geba', 'geba-preintermedia-c', 'GEBA Preintermedia "C"', 'GEBA Preintermedia "C"'),
  (30, 'preintermedia', 'D', '30|preintermedia|D', 'geba', 'geba-preintermedia-d', 'GEBA Preintermedia "D"', 'GEBA Preintermedia "D"'),
  (6, 'preintermedia', '', '6|preintermedia|', 'hindu-club', 'hindu-preintermedia', 'Hindú Preintermedia', 'Hindú Preintermedia'),
  (6, 'preintermedia', 'B', '6|preintermedia|B', 'hindu-club', 'hindu-preintermedia-b', 'Hindú Preintermedia "B"', 'Hindú Preintermedia "B"'),
  (6, 'preintermedia', 'C', '6|preintermedia|C', 'hindu-club', 'hindu-preintermedia-c', 'Hindú Preintermedia "C"', 'Hindú Preintermedia "C"'),
  (6, 'preintermedia', 'D', '6|preintermedia|D', 'hindu-club', 'hindu-preintermedia-d', 'Hindú Preintermedia "D"', 'Hindú Preintermedia "D"'),
  (6, 'preintermedia', 'E', '6|preintermedia|E', 'hindu-club', 'hindu-preintermedia-e', 'Hindú Preintermedia "E"', 'Hindú Preintermedia "E"'),
  (19, 'preintermedia', '', '19|preintermedia|', 'hurling', 'hurling-preintermedia', 'Hurling Preintermedia', 'Hurling Preintermedia'),
  (19, 'preintermedia', 'B', '19|preintermedia|B', 'hurling', 'hurling-preintermedia-b', 'Hurling Preintermedia "B"', 'Hurling Preintermedia "B"'),
  (19, 'preintermedia', 'C', '19|preintermedia|C', 'hurling', 'hurling-preintermedia-c', 'Hurling Preintermedia "C"', 'Hurling Preintermedia "C"'),
  (19, 'preintermedia', 'D', '19|preintermedia|D', 'hurling', 'hurling-preintermedia-d', 'Hurling Preintermedia "D"', 'Hurling Preintermedia "D"'),
  (13, 'preintermedia', '', '13|preintermedia|', 'la-plata', 'la-plata-preintermedia', 'La Plata Preintermedia', 'La Plata Preintermedia'),
  (13, 'preintermedia', 'B', '13|preintermedia|B', 'la-plata', 'la-plata-preintermedia-b', 'La Plata Preintermedia "B"', 'La Plata Preintermedia "B"'),
  (13, 'preintermedia', 'C', '13|preintermedia|C', 'la-plata', 'la-plata-preintermedia-c', 'La Plata Preintermedia "C"', 'La Plata Preintermedia "C"'),
  (13, 'preintermedia', 'D', '13|preintermedia|D', 'la-plata', 'la-plata-preintermedia-d', 'La Plata Preintermedia "D"', 'La Plata Preintermedia "D"'),
  (13, 'preintermedia', 'E', '13|preintermedia|E', 'la-plata', 'la-plata-preintermedia-e', 'La Plata Preintermedia "E"', 'La Plata Preintermedia "E"'),
  (13, 'preintermedia', 'F', '13|preintermedia|F', 'la-plata', 'la-plata-preintermedia-f', 'La Plata Preintermedia "F"', 'La Plata Preintermedia "F"'),
  (51, 'preintermedia', '', '51|preintermedia|', 'lanus-r-c', 'lanus-r-c-preintermedia', 'Lanús R.C. Preintermedia', 'Lanús R.C. Preintermedia'),
  (51, 'preintermedia', 'B', '51|preintermedia|B', 'lanus-r-c', 'lanus-r-c-preintermedia-b', 'Lanús R.C. Preintermedia "B"', 'Lanús R.C. Preintermedia "B"'),
  (36, 'preintermedia', '', '36|preintermedia|', 'liceo-militar', 'liceo-militar-preintermedia', 'Liceo Militar Preintermedia', 'Liceo Militar Preintermedia'),
  (36, 'preintermedia', 'B', '36|preintermedia|B', 'liceo-militar', 'liceo-militar-preintermedia-b', 'Liceo Militar Preintermedia "B"', 'Liceo Militar Preintermedia "B"'),
  (38, 'preintermedia', '', '38|preintermedia|', 'liceo-naval', 'liceo-naval-preintermedia', 'Liceo Naval Preintermedia', 'Liceo Naval Preintermedia'),
  (38, 'preintermedia', 'B', '38|preintermedia|B', 'liceo-naval', 'liceo-naval-preintermedia-b', 'Liceo Naval Preintermedia "B"', 'Liceo Naval Preintermedia "B"'),
  (15, 'preintermedia', '', '15|preintermedia|', 'lomas-athletic', 'lomas-ath-preintermedia', 'Lomas Ath. Preintermedia', 'Lomas Ath. Preintermedia'),
  (15, 'preintermedia', 'B', '15|preintermedia|B', 'lomas-athletic', 'lomas-ath-preintermedia-b', 'Lomas Ath. Preintermedia "B"', 'Lomas Ath. Preintermedia "B"'),
  (15, 'preintermedia', 'C', '15|preintermedia|C', 'lomas-athletic', 'lomas-ath-preintermedia-c', 'Lomas Ath. Preintermedia "C"', 'Lomas Ath. Preintermedia "C"'),
  (15, 'preintermedia', 'D', '15|preintermedia|D', 'lomas-athletic', 'lomas-ath-preintermedia-d', 'Lomas Ath. Preintermedia "D"', 'Lomas Ath. Preintermedia "D"'),
  (23, 'preintermedia', '', '23|preintermedia|', 'los-matreros', 'los-matreros-preintermedia', 'Los Matreros Preintermedia', 'Los Matreros Preintermedia'),
  (23, 'preintermedia', 'B', '23|preintermedia|B', 'los-matreros', 'los-matreros-preintermedia-b', 'Los Matreros Preintermedia "B"', 'Los Matreros Preintermedia "B"'),
  (23, 'preintermedia', 'C', '23|preintermedia|C', 'los-matreros', 'los-matreros-preintermedia-c', 'Los Matreros Preintermedia "C"', 'Los Matreros Preintermedia "C"'),
  (23, 'preintermedia', 'D', '23|preintermedia|D', 'los-matreros', 'los-matreros-preintermedia-d', 'Los Matreros Preintermedia "D"', 'Los Matreros Preintermedia "D"'),
  (65, 'preintermedia', '', '65|preintermedia|', 'los-molinos', 'los-molinos-preintermedia', 'Los Molinos Preintermedia', 'Los Molinos Preintermedia'),
  (65, 'preintermedia', 'B', '65|preintermedia|B', 'los-molinos', 'los-molinos-preintermedia-b', 'Los Molinos Preintermedia "B"', 'Los Molinos Preintermedia "B"'),
  (26, 'preintermedia', '', '26|preintermedia|', 'los-tilos', 'los-tilos-preintermedia', 'Los Tilos Preintermedia', 'Los Tilos Preintermedia'),
  (26, 'preintermedia', 'B', '26|preintermedia|B', 'los-tilos', 'los-tilos-preintermedia-b', 'Los Tilos Preintermedia "B"', 'Los Tilos Preintermedia "B"'),
  (26, 'preintermedia', 'C', '26|preintermedia|C', 'los-tilos', 'los-tilos-preintermedia-c', 'Los Tilos Preintermedia "C"', 'Los Tilos Preintermedia "C"'),
  (26, 'preintermedia', 'D', '26|preintermedia|D', 'los-tilos', 'los-tilos-preintermedia-d', 'Los Tilos Preintermedia "D"', 'Los Tilos Preintermedia "D"'),
  (26, 'preintermedia', 'E', '26|preintermedia|E', 'los-tilos', 'los-tilos-preintermedia-e', 'Los Tilos Preintermedia "E"', 'Los Tilos Preintermedia "E"'),
  (26, 'preintermedia', 'F', '26|preintermedia|F', 'los-tilos', 'los-tilos-preintermedia-f', 'Los Tilos Preintermedia "F"', 'Los Tilos Preintermedia "F"'),
  (26, 'preintermedia', 'G', '26|preintermedia|G', 'los-tilos', 'los-tilos-preintermedia-g', 'Los Tilos Preintermedia "G"', 'Los Tilos Preintermedia "G"'),
  (50, 'preintermedia', '', '50|preintermedia|', 'lujan-r-c', 'lujan-r-c-preintermedia', 'Lujan R.C. Preintermedia', 'Lujan R.C. Preintermedia'),
  (50, 'preintermedia', 'B', '50|preintermedia|B', 'lujan-r-c', 'lujan-r-c-preintermedia-b', 'Lujan R.C. Preintermedia "B"', 'Lujan R.C. Preintermedia "B"'),
  (34, 'preintermedia', '', '34|preintermedia|', 'manuel-belgrano', 'manuel-belgrano-preintermedia', 'Manuel Belgrano Preintermedia', 'Manuel Belgrano Preintermedia'),
  (34, 'preintermedia', 'B', '34|preintermedia|B', 'manuel-belgrano', 'manuel-belgrano-preintermedia-b', 'Manuel Belgrano Preintermedia "B"', 'Manuel Belgrano Preintermedia "B"'),
  (34, 'preintermedia', 'C', '34|preintermedia|C', 'manuel-belgrano', 'manuel-belgrano-preintermedia-c', 'Manuel Belgrano Preintermedia "C"', 'Manuel Belgrano Preintermedia "C"'),
  (39, 'preintermedia', '', '39|preintermedia|', 'mariano-moreno', 'mariano-moreno-preintermedia', 'Mariano Moreno Preintermedia', 'Mariano Moreno Preintermedia'),
  (39, 'preintermedia', 'B', '39|preintermedia|B', 'mariano-moreno', 'mariano-moreno-preintermedia-b', 'Mariano Moreno Preintermedia "B"', 'Mariano Moreno Preintermedia "B"'),
  (39, 'preintermedia', 'C', '39|preintermedia|C', 'mariano-moreno', 'mariano-moreno-preintermedia-c', 'Mariano Moreno Preintermedia "C"', 'Mariano Moreno Preintermedia "C"'),
  (47, 'preintermedia', '', '47|preintermedia|', 'mercedes', 'mercedes-preintermedia', 'Mercedes Preintermedia', 'Mercedes Preintermedia'),
  (41, 'preintermedia', '', '41|preintermedia|', 'monte-grande', 'monte-grande-preintermedia', 'Monte Grande Preintermedia', 'Monte Grande Preintermedia'),
  (41, 'preintermedia', 'B', '41|preintermedia|B', 'monte-grande', 'monte-grande-preintermedia-b', 'Monte Grande Preintermedia "B"', 'Monte Grande Preintermedia "B"'),
  (9, 'preintermedia', '', '9|preintermedia|', 'club-newman', 'newman-preintermedia', 'Newman Preintermedia', 'Newman Preintermedia'),
  (9, 'preintermedia', 'B', '9|preintermedia|B', 'club-newman', 'newman-preintermedia-b', 'Newman Preintermedia "B"', 'Newman Preintermedia "B"'),
  (9, 'preintermedia', 'C', '9|preintermedia|C', 'club-newman', 'newman-preintermedia-c', 'Newman Preintermedia "C"', 'Newman Preintermedia "C"'),
  (9, 'preintermedia', 'D', '9|preintermedia|D', 'club-newman', 'newman-preintermedia-d', 'Newman Preintermedia "D"', 'Newman Preintermedia "D"'),
  (9, 'preintermedia', 'E', '9|preintermedia|E', 'club-newman', 'newman-preintermedia-e', 'Newman Preintermedia "E"', 'Newman Preintermedia "E"'),
  (9, 'preintermedia', 'F', '9|preintermedia|F', 'club-newman', 'newman-preintermedia-f', 'Newman Preintermedia "F"', 'Newman Preintermedia "F"'),
  (9, 'preintermedia', 'G', '9|preintermedia|G', 'club-newman', 'newman-preintermedia-g', 'Newman Preintermedia "G"', 'Newman Preintermedia "G"'),
  (9, 'preintermedia', 'H', '9|preintermedia|H', 'club-newman', 'newman-preintermedia-h', 'Newman Preintermedia "H"', 'Newman Preintermedia "H"'),
  (66, 'preintermedia', '', '66|preintermedia|', 'old-georgian', 'old-georgian-preintermedia', 'Old Georgian Preintermedia', 'Old Georgian Preintermedia'),
  (22, 'preintermedia', '', '22|preintermedia|', 'olivos-r-c', 'olivos-r-c-preintermedia', 'Olivos R.C. Preintermedia', 'Olivos R.C. Preintermedia'),
  (22, 'preintermedia', 'B', '22|preintermedia|B', 'olivos-r-c', 'olivos-r-c-preintermedia-b', 'Olivos R.C. Preintermedia "B"', 'Olivos R.C. Preintermedia "B"'),
  (22, 'preintermedia', 'C', '22|preintermedia|C', 'olivos-r-c', 'olivos-r-c-preintermedia-c', 'Olivos R.C. Preintermedia "C"', 'Olivos R.C. Preintermedia "C"'),
  (22, 'preintermedia', 'D', '22|preintermedia|D', 'olivos-r-c', 'olivos-r-c-preintermedia-d', 'Olivos R.C. Preintermedia "D"', 'Olivos R.C. Preintermedia "D"'),
  (25, 'preintermedia', '', '25|preintermedia|', 'pueyrredon', 'pueyrredon-preintermedia', 'Pueyrredón Preintermedia', 'Pueyrredón Preintermedia'),
  (25, 'preintermedia', 'B', '25|preintermedia|B', 'pueyrredon', 'pueyrredon-preintermedia-b', 'Pueyrredón Preintermedia "B"', 'Pueyrredón Preintermedia "B"'),
  (25, 'preintermedia', 'C', '25|preintermedia|C', 'pueyrredon', 'pueyrredon-preintermedia-c', 'Pueyrredón Preintermedia "C"', 'Pueyrredón Preintermedia "C"'),
  (25, 'preintermedia', 'D', '25|preintermedia|D', 'pueyrredon', 'pueyrredon-preintermedia-d', 'Pueyrredón Preintermedia "D"', 'Pueyrredón Preintermedia "D"'),
  (25, 'preintermedia', 'E', '25|preintermedia|E', 'pueyrredon', 'pueyrredon-preintermedia-e', 'Pueyrredón Preintermedia "E"', 'Pueyrredón Preintermedia "E"'),
  (4, 'preintermedia', '', '4|preintermedia|', 'regatas-de-bella-vista', 'regatas-bv-preintermedia', 'Regatas BV Preintermedia', 'Regatas BV Preintermedia'),
  (4, 'preintermedia', 'B', '4|preintermedia|B', 'regatas-de-bella-vista', 'regatas-bv-preintermedia-b', 'Regatas BV Preintermedia "B"', 'Regatas BV Preintermedia "B"'),
  (4, 'preintermedia', 'C', '4|preintermedia|C', 'regatas-de-bella-vista', 'regatas-bv-preintermedia-c', 'Regatas BV Preintermedia "C"', 'Regatas BV Preintermedia "C"'),
  (4, 'preintermedia', 'D', '4|preintermedia|D', 'regatas-de-bella-vista', 'regatas-bv-preintermedia-d', 'Regatas BV Preintermedia "D"', 'Regatas BV Preintermedia "D"'),
  (4, 'preintermedia', 'E', '4|preintermedia|E', 'regatas-de-bella-vista', 'regatas-bv-preintermedia-e', 'Regatas BV Preintermedia "E"', 'Regatas BV Preintermedia "E"'),
  (14, 'preintermedia', '', '14|preintermedia|', 'san-albano', 'san-albano-preintermedia', 'San Albano Preintermedia', 'San Albano Preintermedia'),
  (14, 'preintermedia', 'B', '14|preintermedia|B', 'san-albano', 'san-albano-preintermedia-b', 'San Albano Preintermedia "B"', 'San Albano Preintermedia "B"'),
  (14, 'preintermedia', 'C', '14|preintermedia|C', 'san-albano', 'san-albano-preintermedia-c', 'San Albano Preintermedia "C"', 'San Albano Preintermedia "C"'),
  (31, 'preintermedia', '', '31|preintermedia|', 'san-andres', 'san-andres-preintermedia', 'San Andrés Preintermedia', 'San Andrés Preintermedia'),
  (31, 'preintermedia', 'B', '31|preintermedia|B', 'san-andres', 'san-andres-preintermedia-b', 'San Andrés Preintermedia "B"', 'San Andrés Preintermedia "B"'),
  (31, 'preintermedia', 'C', '31|preintermedia|C', 'san-andres', 'san-andres-preintermedia-c', 'San Andrés Preintermedia "C"', 'San Andrés Preintermedia "C"'),
  (35, 'preintermedia', '', '35|preintermedia|', 'san-carlos', 'san-carlos-preintermedia', 'San Carlos Preintermedia', 'San Carlos Preintermedia'),
  (35, 'preintermedia', 'B', '35|preintermedia|B', 'san-carlos', 'san-carlos-preintermedia-b', 'San Carlos Preintermedia "B"', 'San Carlos Preintermedia "B"'),
  (18, 'preintermedia', '', '18|preintermedia|', 'san-cirano', 'san-cirano-preintermedia', 'San Cirano Preintermedia', 'San Cirano Preintermedia'),
  (18, 'preintermedia', 'B', '18|preintermedia|B', 'san-cirano', 'san-cirano-preintermedia-b', 'San Cirano Preintermedia "B"', 'San Cirano Preintermedia "B"'),
  (18, 'preintermedia', 'C', '18|preintermedia|C', 'san-cirano', 'san-cirano-preintermedia-c', 'San Cirano Preintermedia "C"', 'San Cirano Preintermedia "C"'),
  (18, 'preintermedia', 'D', '18|preintermedia|D', 'san-cirano', 'san-cirano-preintermedia-d', 'San Cirano Preintermedia "D"', 'San Cirano Preintermedia "D"'),
  (18, 'preintermedia', 'E', '18|preintermedia|E', 'san-cirano', 'san-cirano-preintermedia-e', 'San Cirano Preintermedia "E"', 'San Cirano Preintermedia "E"'),
  (32, 'preintermedia', '', '32|preintermedia|', 'san-fernando', 'san-fernando-preintermedia', 'San Fernando Preintermedia', 'San Fernando Preintermedia'),
  (32, 'preintermedia', 'B', '32|preintermedia|B', 'san-fernando', 'san-fernando-preintermedia-b', 'San Fernando Preintermedia "B"', 'San Fernando Preintermedia "B"'),
  (32, 'preintermedia', 'C', '32|preintermedia|C', 'san-fernando', 'san-fernando-preintermedia-c', 'San Fernando Preintermedia "C"', 'San Fernando Preintermedia "C"'),
  (5, 'preintermedia', '', '5|preintermedia|', 'san-luis', 'san-luis-preintermedia', 'San Luis Preintermedia', 'San Luis Preintermedia'),
  (5, 'preintermedia', 'B', '5|preintermedia|B', 'san-luis', 'san-luis-preintermedia-b', 'San Luis Preintermedia "B"', 'San Luis Preintermedia "B"'),
  (5, 'preintermedia', 'C', '5|preintermedia|C', 'san-luis', 'san-luis-preintermedia-c', 'San Luis Preintermedia "C"', 'San Luis Preintermedia "C"'),
  (5, 'preintermedia', 'D', '5|preintermedia|D', 'san-luis', 'san-luis-preintermedia-d', 'San Luis Preintermedia "D"', 'San Luis Preintermedia "D"'),
  (5, 'preintermedia', 'E', '5|preintermedia|E', 'san-luis', 'san-luis-preintermedia-e', 'San Luis Preintermedia "E"', 'San Luis Preintermedia "E"'),
  (20, 'preintermedia', '', '20|preintermedia|', 'san-martin', 'san-martin-preintermedia', 'San Martín Preintermedia', 'San Martín Preintermedia'),
  (20, 'preintermedia', 'B', '20|preintermedia|B', 'san-martin', 'san-martin-preintermedia-b', 'San Martín Preintermedia "B"', 'San Martín Preintermedia "B"'),
  (20, 'preintermedia', 'C', '20|preintermedia|C', 'san-martin', 'san-martin-preintermedia-c', 'San Martín Preintermedia "C"', 'San Martín Preintermedia "C"'),
  (20, 'preintermedia', 'D', '20|preintermedia|D', 'san-martin', 'san-martin-preintermedia-d', 'San Martín Preintermedia "D"', 'San Martín Preintermedia "D"'),
  (56, 'preintermedia', '', '56|preintermedia|', 'san-miguel-r-c', 'san-miguel-preintermedia', 'San Miguel Preintermedia', 'San Miguel Preintermedia'),
  (21, 'preintermedia', '', '21|preintermedia|', 'club-san-patricio', 'san-patricio-preintermedia', 'San Patricio Preintermedia', 'San Patricio Preintermedia'),
  (21, 'preintermedia', 'B', '21|preintermedia|B', 'club-san-patricio', 'san-patricio-preintermedia-b', 'San Patricio Preintermedia "B"', 'San Patricio Preintermedia "B"'),
  (1, 'preintermedia', '', '1|preintermedia|', 'san-isidro-club', 'sic-preintermedia', 'SIC Preintermedia', 'SIC Preintermedia'),
  (1, 'preintermedia', 'B', '1|preintermedia|B', 'san-isidro-club', 'sic-preintermedia-b', 'SIC Preintermedia "B"', 'SIC Preintermedia "B"'),
  (1, 'preintermedia', 'C', '1|preintermedia|C', 'san-isidro-club', 'sic-preintermedia-c', 'SIC Preintermedia "C"', 'SIC Preintermedia "C"'),
  (1, 'preintermedia', 'D', '1|preintermedia|D', 'san-isidro-club', 'sic-preintermedia-d', 'SIC Preintermedia "D"', 'SIC Preintermedia "D"'),
  (1, 'preintermedia', 'E', '1|preintermedia|E', 'san-isidro-club', 'sic-preintermedia-e', 'SIC Preintermedia "E"', 'SIC Preintermedia "E"'),
  (1, 'preintermedia', 'F', '1|preintermedia|F', 'san-isidro-club', 'sic-preintermedia-f', 'SIC Preintermedia "F"', 'SIC Preintermedia "F"'),
  (1, 'preintermedia', 'G', '1|preintermedia|G', 'san-isidro-club', 'sic-preintermedia-g', 'SIC Preintermedia "G"', 'SIC Preintermedia "G"'),
  (43, 'preintermedia', '', '43|preintermedia|', 'sitas', 'sitas-preintermedia', 'SITAS Preintermedia', 'SITAS Preintermedia'),
  (43, 'preintermedia', 'B', '43|preintermedia|B', 'sitas', 'sitas-preintermedia-b', 'SITAS Preintermedia "B"', 'SITAS Preintermedia "B"'),
  (58, 'preintermedia', '', '58|preintermedia|', 'st-brendan-s', 'st-brendans-preintermedia', 'St. Brendan''s Preintermedia', 'St. Brendan''s Preintermedia'),
  (72, 'preintermedia', '', '72|preintermedia|', 'tigre', 'tigre-preintermedia', 'Tigre Preintermedia', 'Tigre Preintermedia'),
  (29, 'preintermedia', '', '29|preintermedia|', 'universitario-de-la-plata', 'univ-la-plata-preintermedia', 'Univ. La Plata Preintermedia', 'Univ. La Plata Preintermedia'),
  (29, 'preintermedia', 'B', '29|preintermedia|B', 'universitario-de-la-plata', 'univ-la-plata-preintermedia-b', 'Univ. La Plata Preintermedia "B"', 'Univ. La Plata Preintermedia "B"'),
  (45, 'preintermedia', '', '45|preintermedia|', 'vicentinos', 'vicentinos-preintermedia', 'Vicentinos Preintermedia', 'Vicentinos Preintermedia'),
  (45, 'preintermedia', 'B', '45|preintermedia|B', 'vicentinos', 'vicentinos-preintermedia-b', 'Vicentinos Preintermedia "B"', 'Vicentinos Preintermedia "B"'),
  (55, 'preintermedia', '', '55|preintermedia|', 'virreyes-r-c', 'virreyes-r-c-preintermedia', 'Virreyes R.C. Preintermedia', 'Virreyes R.C. Preintermedia'),
  (55, 'preintermedia', 'B', '55|preintermedia|B', 'virreyes-r-c', 'virreyes-r-c-preintermedia-b', 'Virreyes R.C. Preintermedia "B"', 'Virreyes R.C. Preintermedia "B"'),
  (97, 'universitario', '', '97|universitario|', 'cune', 'cune-universitario', 'CUNE Universitario', 'CUNE Universitario'),
  (96, 'universitario', '', '96|universitario|', 'uca-la-plata', 'uca-la-plata-universitario', 'UCA la Plata Universitario', 'UCA la Plata Universitario'),
  (106, 'universitario', '', '106|universitario|', 'univ-nac-de-la-matanza', 'univ-nac-de-la-matanza-universitario', 'Univ. Nac de la Matanza Universitario', 'Univ. Nac de la Matanza Universitario'),
  (95, 'universitario', '', '95|universitario|', 'univ-nac-de-la-plata', 'univ-nac-de-la-plata-universitario', 'Univ. Nac de la Plata Universitario', 'Univ. Nac de la Plata Universitario')
ON CONFLICT (external_id) DO NOTHING;

COMMIT;

-- VERIFICACIÓN
-- SELECT count(*) FROM public.stg_urba_equipos_mayores;
-- esperado acumulado tras la parte 1: 332
-- (no hay más partes)
