BEGIN;

CREATE OR REPLACE FUNCTION public.normalize_telegram_phone_number(phone TEXT)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
RETURNS NULL ON NULL INPUT
SET search_path = public
AS $$
    SELECT NULLIF(regexp_replace(phone, '[^0-9]+', '', 'g'), '');
$$;

CREATE TABLE IF NOT EXISTS public.admin_telegram_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_user_id BIGINT UNIQUE,
    telegram_phone_number TEXT NOT NULL UNIQUE,
    username TEXT,
    first_name TEXT,
    last_name TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.admin_telegram_users
    ADD COLUMN IF NOT EXISTS telegram_user_id BIGINT,
    ADD COLUMN IF NOT EXISTS telegram_phone_number TEXT,
    ADD COLUMN IF NOT EXISTS username TEXT,
    ADD COLUMN IF NOT EXISTS first_name TEXT,
    ADD COLUMN IF NOT EXISTS last_name TEXT,
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

UPDATE public.admin_telegram_users
SET is_active = TRUE
WHERE is_active IS NULL;

ALTER TABLE public.admin_telegram_users
    ALTER COLUMN telegram_phone_number SET NOT NULL,
    ALTER COLUMN is_active SET NOT NULL,
    ALTER COLUMN is_active SET DEFAULT TRUE,
    ALTER COLUMN created_at SET DEFAULT NOW();

DO $$
BEGIN
    ALTER TABLE public.admin_telegram_users
        ADD CONSTRAINT admin_telegram_users_phone_not_blank
        CHECK (public.normalize_telegram_phone_number(telegram_phone_number) IS NOT NULL);
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS admin_telegram_users_telegram_user_id_key
    ON public.admin_telegram_users (telegram_user_id)
    WHERE telegram_user_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS admin_telegram_users_phone_digits_key
    ON public.admin_telegram_users (public.normalize_telegram_phone_number(telegram_phone_number));

CREATE INDEX IF NOT EXISTS idx_admin_telegram_users_active_phone
    ON public.admin_telegram_users (public.normalize_telegram_phone_number(telegram_phone_number))
    WHERE is_active = TRUE;

CREATE OR REPLACE FUNCTION public.is_admin_telegram_user_authorized(
    p_telegram_user_id BIGINT DEFAULT NULL,
    p_telegram_phone_number TEXT DEFAULT NULL
)
RETURNS TABLE (
    authorized BOOLEAN,
    id BIGINT,
    telegram_user_id BIGINT,
    telegram_phone_number TEXT,
    username TEXT,
    first_name TEXT,
    last_name TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
DECLARE
    normalized_phone TEXT := public.normalize_telegram_phone_number(p_telegram_phone_number);
BEGIN
    RETURN QUERY
    SELECT
        TRUE AS authorized,
        u.id,
        u.telegram_user_id,
        u.telegram_phone_number,
        u.username,
        u.first_name,
        u.last_name
    FROM public.admin_telegram_users AS u
    WHERE u.is_active = TRUE
      AND (
          (p_telegram_user_id IS NOT NULL AND u.telegram_user_id = p_telegram_user_id)
          OR (
              normalized_phone IS NOT NULL
              AND public.normalize_telegram_phone_number(u.telegram_phone_number) = normalized_phone
          )
      )
    ORDER BY
        CASE
            WHEN p_telegram_user_id IS NOT NULL AND u.telegram_user_id = p_telegram_user_id THEN 0
            ELSE 1
        END,
        u.created_at ASC
    LIMIT 1;

    IF NOT FOUND THEN
        RETURN QUERY
        SELECT
            FALSE,
            NULL::BIGINT,
            NULL::BIGINT,
            NULL::TEXT,
            NULL::TEXT,
            NULL::TEXT,
            NULL::TEXT;
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.link_admin_telegram_user_identity(
    p_telegram_user_id BIGINT,
    p_telegram_phone_number TEXT,
    p_username TEXT DEFAULT NULL,
    p_first_name TEXT DEFAULT NULL,
    p_last_name TEXT DEFAULT NULL
)
RETURNS TABLE (
    linked BOOLEAN,
    id BIGINT,
    telegram_user_id BIGINT,
    telegram_phone_number TEXT,
    username TEXT,
    first_name TEXT,
    last_name TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
VOLATILE
SET search_path = public
AS $$
DECLARE
    normalized_phone TEXT := public.normalize_telegram_phone_number(p_telegram_phone_number);
BEGIN
    IF p_telegram_user_id IS NULL OR normalized_phone IS NULL THEN
        RETURN QUERY
        SELECT FALSE, NULL::BIGINT, NULL::BIGINT, NULL::TEXT, NULL::TEXT, NULL::TEXT, NULL::TEXT;
        RETURN;
    END IF;

    RETURN QUERY
    UPDATE public.admin_telegram_users AS u
    SET
        telegram_user_id = p_telegram_user_id,
        username = COALESCE(NULLIF(trim(p_username), ''), u.username),
        first_name = COALESCE(NULLIF(trim(p_first_name), ''), u.first_name),
        last_name = COALESCE(NULLIF(trim(p_last_name), ''), u.last_name)
    WHERE u.is_active = TRUE
      AND public.normalize_telegram_phone_number(u.telegram_phone_number) = normalized_phone
      AND (u.telegram_user_id IS NULL OR u.telegram_user_id = p_telegram_user_id)
    RETURNING
        TRUE AS linked,
        u.id,
        u.telegram_user_id,
        u.telegram_phone_number,
        u.username,
        u.first_name,
        u.last_name;

    IF NOT FOUND THEN
        RETURN QUERY
        SELECT FALSE, NULL::BIGINT, NULL::BIGINT, NULL::TEXT, NULL::TEXT, NULL::TEXT, NULL::TEXT;
    END IF;
END;
$$;

ALTER TABLE public.admin_telegram_users ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF to_regprocedure('public.authorize_admin()') IS NOT NULL THEN
        EXECUTE 'DROP POLICY IF EXISTS admin_telegram_users_admin_manage ON public.admin_telegram_users';
        EXECUTE 'CREATE POLICY admin_telegram_users_admin_manage ON public.admin_telegram_users
            FOR ALL TO authenticated
            USING (public.authorize_admin())
            WITH CHECK (public.authorize_admin())';
    END IF;
END $$;

GRANT USAGE ON SCHEMA public TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.admin_telegram_users TO authenticated, service_role;

DO $$
BEGIN
    IF to_regclass('public.admin_telegram_users_id_seq') IS NOT NULL THEN
        GRANT USAGE, SELECT ON SEQUENCE public.admin_telegram_users_id_seq TO authenticated, service_role;
    END IF;
END $$;

REVOKE ALL ON FUNCTION public.normalize_telegram_phone_number(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.is_admin_telegram_user_authorized(BIGINT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.link_admin_telegram_user_identity(BIGINT, TEXT, TEXT, TEXT, TEXT) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.normalize_telegram_phone_number(TEXT) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_admin_telegram_user_authorized(BIGINT, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.link_admin_telegram_user_identity(BIGINT, TEXT, TEXT, TEXT, TEXT) TO service_role;

COMMENT ON TABLE public.admin_telegram_users IS 'Telegram bot allowlist for admin users, keyed by Telegram phone number and optionally linked to Telegram user id.';
COMMENT ON FUNCTION public.is_admin_telegram_user_authorized(BIGINT, TEXT) IS 'Checks whether a Telegram user id or shared phone number belongs to an active bot admin.';
COMMENT ON FUNCTION public.link_admin_telegram_user_identity(BIGINT, TEXT, TEXT, TEXT, TEXT) IS 'Links a verified Telegram contact phone to the sender user id after the bot receives a self-shared contact.';

COMMIT;
